### ISSUE TITLE
Adding Contact Us Page

### ISSUE THREAD

**Issue by Gauravtb2253** [Tejashri-Taral/TrendTrove-Ecommerce#1]
Hello I would like to add contact page to the project
Please assign this to me

Thank you

**Comment by NikitaYewale007** [comment]
hey, i love to work on this, can you assign me?

**Comment by SaanyaGarg5** [comment]
i can work on it ..assign that task to me

**Comment by bhavanireddy57** [comment]
can u please assign this to me I want to work on this.
