### ISSUE TITLE
Adding a functionality of Liked Products

### ISSUE THREAD

**Issue by akansha204** [Tejashri-Taral/TrendTrove-Ecommerce#101]
Hi @Tejashri-Taral 
I want to implement a feature of Liked products.

Please assign this to me under gssoc'24(extd)

**Comment by Tejashri-Taral** [comment]
Level will be assigned based on work

**Comment by Tejashri-Taral** [comment]
@akansha204 Any update?

**Comment by akansha204** [comment]
Hey can you please assign me the level first

**Comment by Tejashri-Taral** [comment]
It's been more than 12 days and I'm closing this issue
I have mention that after your work I'll add level but you didn't make any changes
