### ISSUE TITLE
navigation bar hover on about 

### ISSUE THREAD

**Issue by rohir1132yadav** [Tejashri-Taral/TrendTrove-Ecommerce#102]
Hover in  navigation bar are not working and i want to remove the underline below the  feature ,contact us and product and i also want to change the color during hover .

**Comment by rohir1132yadav** [comment]
i want to work on this issue #102 .please assign me.

**Comment by ruchit2005** [comment]
HI,
I see that the underline below "About" is not working and to maintain uniformity u want to remove it from  feature, contact us and product as well... In my opinion , if we add the underline to all the tags, it would look better, but if u wish it the other way , it's absolutely fine.
During the hover we can change the color as well as the SIZE of the text which will make it look even better. 
I would like to contribute and solve this issue #102 and make it better

**Comment by rohir1132yadav** [comment]
bro you are assign me this issue but you aare closed now without checking it

**Comment by rohir1132yadav** [comment]
Please assign me again ,I have work on it a lot

**Comment by rohir1132yadav** [comment]
It's mean it has count on my hactoberfest also
