### ISSUE TITLE
I want to update README.md file 

### ISSUE THREAD

**Issue by JahnavikaGopalbvrith** [Tejashri-Taral/TrendTrove-Ecommerce#104]
Key points that will enhance the README file include installation instructions, a usage guide, visual representations, API documentation, and a section on future features and improvements.

**Comment by Tejashri-Taral** [comment]
What changes are you planning to do?

**Comment by JahnavikaGopalbvrith** [comment]
I want to include 
project purpose and vision
Preview Link
Future Improvements 
Changelog- track progress and version changes
