### ISSUE TITLE
Addition of well-designed buttons.

### ISSUE THREAD

**Issue by maliumesh1** [Tejashri-Taral/TrendTrove-Ecommerce#11]
![Screenshot 2024-10-01 193538](https://github.com/user-attachments/assets/8aac2a96-6ca0-446d-a7c3-d256209ddb31)

The user experience and engagement of your product display area can be greatly enhanced by the addition of well-designed buttons.
Please Assign me this Task

**Comment by Priyanshi231** [comment]
Hello Maintainers,

I would like to work on adding well-designed buttons to the project. Here’s what I propose for the implementation:

Task Overview:
I will add custom-designed buttons for different sections of the project, ensuring that they are consistent with the overall design language.

Design & Styling:
The buttons will be styled with:
Color schemes: Matching the project’s theme (primary color for important actions, secondary for less prominent actions).
Hover effects: Subtle changes in color, shadow, or animation to improve the user experience.
Rounded corners or sharp edges: Depending on the project’s design guidelines.
Responsive design: Ensuring the buttons look and function well on all devices (desktop, tablet, and mobile).

Please let me know if I can be assigned to this task. I’m looking forward to contributing!

Thank you!
