### ISSUE TITLE
Update Product Name and Price Display Section

### ISSUE THREAD

**Issue by iamasraful** [Tejashri-Taral/TrendTrove-Ecommerce#110]
The current product section displays product names and prices in two lines beneath each image. I want to make the following changes:

Align each product name and its price closer to the image of the product.
Format the product name and price in a single line, directly below the image for each item.
Ensure proper spacing and consistent styling across all items (font size, color, etc.).

![image](https://github.com/user-attachments/assets/06838998-1c37-4725-8fcf-99d5629ed2ee)
![image](https://github.com/user-attachments/assets/51815338-76bf-4a74-b512-d1b91c6aafd3)

**Comment by tulikaa25** [comment]
Please assign this issue to me. @Tejashri-Taral
