### ISSUE TITLE
Footer adjustment

### ISSUE THREAD

**Issue by dagiz6** [Tejashri-Taral/TrendTrove-Ecommerce#12]
the footer needs some upgrades, the fonts are very large , the font is not attractive , the button and form have some collision , In general, it is not attractive . Please assign me this task, and I will make it beautiful.

**Comment by Tejashri-Taral** [comment]
Can you elaborate and share the design?

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than a week, and the website is now updated with new changes
