### ISSUE TITLE
FIXING NAVBAR overflow

### ISSUE THREAD

**Issue by sahhoArjun097** [Tejashri-Taral/TrendTrove-Ecommerce#121]
the navbar content is overflowing that seems Unappropriate .
 i can fix this issue and fix the overflow .

![image](https://github.com/user-attachments/assets/45fbacd0-ab86-4b57-a30e-5fc8c2edfdff)
Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

**Comment by hars-21** [comment]
Go ahead. Also, fix the navbar in mobile view.

**Comment by shubham7522** [comment]
Can work on this issue?

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than a week, and the website is now updated with new changes
