### ISSUE TITLE
 Adding Hover Effect to All Buttons

### ISSUE THREAD

**Issue by Abhishek-TG18** [Tejashri-Taral/TrendTrove-Ecommerce#125]
Currently, none of the buttons across the site have a hover effect, which affects the overall user experience. The task is to add a hover effect to all buttons, enhancing interactivity and visual feedback when users interact with them. Ensure that the hover effect is consistent across the website, with a smooth transition that complements the existing design.

Requirements:

Apply a subtle hover effect (e.g., color change, shadow, or background shift) to all buttons.
Ensure that the effect is responsive and works well across all devices.
Implement the hover effect using CSS.

**Comment by Abhishek-TG18** [comment]
@Tejashri-Taral please add gssoc-ext  and hacktober tag

**Comment by PiyushVIT346** [comment]
Please assign this task to me . Hover all the button as per the template related changes in UI also.

**Comment by ruchit2005** [comment]
HI,
I see that the underline below "About" is not working and to maintain uniformity u want to remove it from feature, contact us and product as well... In my opinion , if we add the underline to all the tags, it would look better, but if u wish it the other way , it's absolutely fine.
During the hover we can change the color as well as the SIZE of the text which will make the overall UI look even better. I would like to contribute and solve this issue .

**Comment by eshitatalukdar08** [comment]
Hello, please assign me to this task. Applying hover effects, along with other enhancements such as shadows and bold styles, will uplift the overall look of the website. These effects include changes in color, font size, borders, and more in the buttons, with additional animations for a short interval of time. I am excited to contribute and take the user experience to the next level!

**Comment by ChauhanAyush04** [comment]
@Tejashri-Taral  plz assign me
