### ISSUE TITLE
[FEATURE] Show Newsletter Subscription Confirmation Message

### ISSUE THREAD

**Issue by Anwishta** [Tejashri-Taral/TrendTrove-Ecommerce#143]
### Description:
We need to enhance the user experience by displaying a clear and user-friendly confirmation message after successful subscription to our newsletter. This will inform users that their subscription was successful and that they will start receiving updates from us.

![Screenshot 2024-10-05 190034](https://github.com/user-attachments/assets/81c32742-54df-4c77-bbea-dcfcb150b872)

### Expected Behavior:
A logic should be implemented to check whether the email is correct or not.
After submitting the email on the newsletter sign-up form, users should see a confirmation message.
The message should appear on the same page without redirecting the user.

Kindly assign me this issue

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by Anwishta** [comment]
Almost done. I'll try to make a PR by tomorrow.
