### ISSUE TITLE
Terms and Conditions and return policy Page

### ISSUE THREAD

**Issue by 00Himnshi** [Tejashri-Taral/TrendTrove-Ecommerce#156]
Both Terms and Conditions and return policy Pages seems to be missing , i would like to work on them .Please assign these to me under gsoc ext.

**Comment by Tejashri-Taral** [comment]
Go ahead

**Comment by Supraja-Gao** [comment]
Tejashri-Taral please assign this issue to me also.. I will work on this issue.

**Comment by Deepikajyothi007** [comment]
I would like to add terms and conditions and return policy page, please assign this to me @Tejashri-Taral

**Comment by 00Himnshi** [comment]
> I would like to add terms and conditions and return policy page, please assign this to me @Tejashri-Taral

i am already working on return policy page.
