### ISSUE TITLE
Improve About Section

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [Tejashri-Taral/TrendTrove-Ecommerce#161]
I would like to make about section more user friendly rather than just being like a pdf page.
![Screenshot 2024-10-06 030254](https://github.com/user-attachments/assets/f9e0110c-88e8-4fe9-ac0a-d5105a106046)
I will improve this page. Please assign me the task @Tejashri-Taral

**Comment by Supraja-Gao** [comment]
Tejashri-Taral please assign this issue to me also.. I would like to work on this issue

**Comment by Adarsh-Chaubey03** [comment]
created #181
