### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by BVaishnavi15** [Tejashri-Taral/TrendTrove-Ecommerce#164]
Want  to enhance contact page as it shows a basic form

**Comment by poojapoojanr** [comment]
@Tejashri-Taral Can you please assign me this under GSSoC-EXTD and Hacktoberfest accepted.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by BVaishnavi15** [comment]
okay

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by BVaishnavi15** [comment]
yes its done
