### ISSUE TITLE
Enhancement of Sneakers Page: Filters Section and Additional Listings

### ISSUE THREAD

**Issue by Lonewolf124** [Tejashri-Taral/TrendTrove-Ecommerce#169]
I have been working on enhancing the Sneakers page to improve user experience and product discoverability. These enhancements focus on two main areas:

**1. Addition of a Filters Section:**

This new feature will allow users to refine their search based on various parameters, making it easier to find the products they want. The filters have been designed to be user-friendly and intuitive.

**2. Expanded Sneaker Catalog:**

I have also added several new sneakers to the page to ensure a broader selection of products for users to browse. These new listings include all relevant product details, ensuring a consistent and appealing look for the page.

I have already completed the development work on these improvements and would be happy to raise a pull request for review once the issue is assigned to me.

I am a gssoc-ext and hacktoberfest contributor

**Comment by hars-21** [comment]
Proceed!

**Comment by Lonewolf124** [comment]
> Proceed!

Hii @hars-21 
I've completed the enhancements for the Sneakers page, including adding a filter section and additional sneaker options.

Also, I noticed that the **level label**  has not yet been added to my issue. Could you please add it? 

Thank you!
