### ISSUE TITLE
Enhancement of Sign up and Login Page 

### ISSUE THREAD

**Issue by AfrozeSVU** [Tejashri-Taral/TrendTrove-Ecommerce#170]
There is no proper styling in both sign up and Login page like spacing and hover states . I would like to add javascript functionalities to  it like  
adding remember me check box
agree to terms and conditions check box
 Enabling Sign up and login button after all the input fields are filled 

I will work on Overall styling of the page for effective look 
 I am a gssoc-ext and hacktoberfest contributor

@Tejashri-Taral Assign me so that I can work on it

![Screenshot 2024-10-06 123943](https://github.com/user-attachments/assets/6737fe49-a5c8-4f1d-8e03-5600e1195df3)

![Screenshot 2024-10-06 124011](https://github.com/user-attachments/assets/a3e502bb-c2b1-4105-9611-86c403e7b893)

**Comment by hars-21** [comment]
Proceed!

**Comment by himanchal08** [comment]
Hi @hars-21 ,

Could you please assign this issue to me? I would love to work on it. Give this whole website a new styling that will match the theme of the brand . 
Two options that I offer :
1-> Translucent look to the login and signup cards and add nice background .
2-> Add some animation when on click will take action . 

Thank you!
Himanchal
