### ISSUE TITLE
FEATURE : Sidebar navigation

### ISSUE THREAD

**Issue by archanasingh11** [Tejashri-Taral/TrendTrove-Ecommerce#174]
**Description:**

The TrendTrove-Ecommerce website currently lacks a **sidebar navigation menu**, which can greatly enhance the user experience by providing easy access to various product categories, filters, and account options. Implementing a responsive and user-friendly sidebar menu will help users navigate the website more efficiently, particularly on pages with a large variety of products.

Suggested features for the sidebar menu:
- Collapsible categories and subcategories for product browsing.
- Filters for sorting products by price, popularity, and ratings.
- Quick links to user account, cart, and order history.
- Responsive design for optimal viewing on both desktop and mobile devices.

Adding a sidebar navigation menu will improve usability, help users find products faster, and make the overall shopping experience more intuitive.

Please @Tejashri-Taral  assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by archanasingh11** [comment]
i will complete this by tonight

**Comment by archanasingh11** [comment]
My exams are goin g on I 'll complete it by today itself

**Comment by archanasingh11** [comment]
I'm facing problem in css part because due to my css code my orientation is not fitting in
![Screenshot (105)](https://github.com/user-attachments/assets/66ed2531-cd9b-4dae-b511-3242d6c4a83c)
![Screenshot (106)](https://github.com/user-attachments/assets/a02fd9b3-0a2c-4c02-b907-ef59fb7e6b50)
this are sample which i would like to incoporate on the website

**Comment by hars-21** [comment]
Please describe the problem you are facing then only we will be able to resolve it. @archanasingh11

**Comment by archanasingh11** [comment]
while using css
what css properties im using its not showing up due others css properties so changing entire css for the website will be risky job

**Comment by hars-21** [comment]
@archanasingh11 I am closing this issue for now. If you want you proceed further, you can create a new issue.
