### ISSUE TITLE
Feature: Add a Scroll "Progress Indicator Bar"

### ISSUE THREAD

**Issue by JHA-geek-AYUSH** [Tejashri-Taral/TrendTrove-Ecommerce#179]
## Describe the Feature
Hey @Tejashri-Taral,

I want to add a **Scroll Down Progress Bar** to the website.

### Feature Description:
This feature adds a progress bar that visually indicates the user's scroll progress as they move down the page. It enhances the user experience by providing a clear visual cue of their current position on the page and how much content is left to be viewed.

### Benefits:
- Improves **user engagement** by offering a sense of progression.
- Offers a **better navigation experience** for longer pages with substantial content.

### Screenshot:
![design](https://github.com/user-attachments/assets/d9042b5d-5d99-4356-b5d9-7b71e5b6c568)

**Comment by Tejashri-Taral** [comment]
Go ahead

**Comment by Shalinis19137** [comment]
Yours website is such a wonderful website and I really like it . But in this website feature bar is not working / Clickable I want to improve this please assign me this issue.
![Uploading Screenshot 2024-10-06 213226.png…]()
