### ISSUE TITLE
Fixing the navbar

### ISSUE THREAD

**Issue by ayushijainn111** [Tejashri-Taral/TrendTrove-Ecommerce#2]
The navbar has sections that need spacing. We can also add some animations and hover effects to make it look responsive

<img width="397" alt="Screenshot 2024-10-01 182331" src="https://github.com/user-attachments/assets/10ef1ea4-adc5-410a-b7a4-e326bde03857">
@Tejashri-Taral Assign this to me!

**Comment by SaanyaGarg5** [comment]
i can work on it..assign that task to me

**Comment by Ishajain0** [comment]
I can work on it please assign this task  to me ...

**Comment by ayushijainn111** [comment]
@Tejashri-Taral hey i made the required changes and raised a pull request so can you check that out please?
