### ISSUE TITLE
Navbar Hover and Link Issues

### ISSUE THREAD

**Issue by Pmaheshwari11** [Tejashri-Taral/TrendTrove-Ecommerce#201]
Hello, I've noticed a few issues with the navbar and would like to contribute by fixing them. 

Here are the problems I've observed:
**Hovering Issue**: Some elements in the navbar do not respond properly to hovering, making it difficult to navigate.
**Link Issue**: When navigating to the "Feature" page via the navbar, the "Product" link does not function as expected.  And on "Contact" page the link to "Feature" page is not correct.

Proposed Solution: I would like to work on these issues by:
Fixing the hover functionality to ensure all navbar elements respond smoothly.
Investigating and resolving the issue with the "Product" link on the "Feature" page to ensure proper navigation.

Could you please grant me permission to apply these changes?

![Screenshot 2024-10-07 094631](https://github.com/user-attachments/assets/a044860c-b16a-4603-81ec-60301b335ceb)
![Screenshot 2024-10-07 094656](https://github.com/user-attachments/assets/bf003369-5077-4805-b050-fce6b3aa8b20)

**Comment by Bhumika-00** [comment]
Can you please assign this task to me I can resolve this problem and provide the best possible solution.
