### ISSUE TITLE
Google Authentication using Firebase

### ISSUE THREAD

**Issue by samriddhitiwary** [Tejashri-Taral/TrendTrove-Ecommerce#210]
This feature would allow users to log in quickly and securely using their Google accounts, streamlining the authentication process and improving user experience. It can also enhance security by relying on Google’s authentication infrastructure.

![image](https://github.com/user-attachments/assets/6f970126-da7f-4493-8135-403a34c004b5)

**Comment by AbrerAsif07** [comment]
Pls assign this issue to me under gssoc-ext and hhacktoberfest label.
