### ISSUE TITLE
[BUG] Preset for github Issues

### ISSUE THREAD

**Issue by 4F24L** [Tejashri-Taral/TrendTrove-Ecommerce#212]
## #Preset for Github Issues
- I can make a preset for github issues
- Two form can be created.
- BUG and Feature form

![image](https://github.com/user-attachments/assets/fe6ad391-d2ba-43c9-bc7c-14776e0cf2ff)
##

### #Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by 4F24L** [comment]
Why reopened this ??
