### ISSUE TITLE
NAVBAR-HOVER

### ISSUE THREAD

**Issue by shivigoyal4321** [Tejashri-Taral/TrendTrove-Ecommerce#215]
### **Issue Title**
Navbar Hover Property Not Working.

### **Navbar Hover Property:** **The hover effect on the navbar does not work as expected. _When I hover over the ABOUT and PRODUCTS, there is no (underline hover)  change_, which may affect user experience.**

I'd be glad to help resolve this issue if it can be assigned to me.

i have explained the issue through a video also.

https://github.com/user-attachments/assets/5021bc7b-0902-45a5-bc4e-ad857ed42fde

**Comment by Tejashri-Taral** [comment]
Someone already added that
