### ISSUE TITLE
Card description wrong alignment 

### ISSUE THREAD

**Issue by Risheendra183** [Tejashri-Taral/TrendTrove-Ecommerce#22]
i would like to change the alignment of product and cost ,and cursor on the add to wishlist .
please assign me and label Gsscoc-ext and level
![image](https://github.com/user-attachments/assets/32cda154-3e3f-4506-913f-8ac07ef9ea34)

**Comment by rohitsharma2610** [comment]
Hey, i have experience in this work so can you assign me?

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than a week, and the website is now updated with new changes
