### ISSUE TITLE
Scrolling Behavior for better UX (User Experience) in Product page

### ISSUE THREAD

**Issue by Sonalika003** [Tejashri-Taral/TrendTrove-Ecommerce#220]
When clicking on any nav icon, it navigates to the section.
However this navigation is not smooth, and feels rough for user.
Having a smooth navigation would be better experience for customer journey.

https://github.com/user-attachments/assets/982bd8ed-f3fb-466b-93ae-65972fe3c09b

added better version for it.

https://github.com/user-attachments/assets/bcc30ed4-ca14-454d-9ade-060ae0416696

**Comment by Sonalika003** [comment]
I would really like to work on it! Please assign it to me.

Also assign relevant labels (GSSOC ext) , good first issue

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Sonalika003** [comment]
I almost done with that, along with that found one more issue related to product nav link may I also fix that and report in PR

**Comment by Sonalika003** [comment]
https://github.com/user-attachments/assets/4e10f76a-8ab6-442c-b035-3128126eeaba
