### ISSUE TITLE
Fix navigation bar to remain at the top while scrolling

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [Tejashri-Taral/TrendTrove-Ecommerce#225]
Current Behavior: The navigation bar scrolls along with the page content, making it disappear when the user scrolls down. This reduces ease of access and navigation, as users have to scroll back to the top to access the menu items.

Expected Behavior: The navigation bar should be fixed at the top of the page so that it remains visible and accessible regardless of the scroll position.

Plz assign tag of hacktoberfest accepted and level for gssoc 2024 extended
Thank you @Tejashri-Taral 
![Screenshot 2024-10-07 222731](https://github.com/user-attachments/assets/c937a0b3-6838-4438-b5fc-1df4f21ed6d2)

**Comment by harshpareshbhaigosalya** [comment]
I have already completed the fix and am just waiting for you to assign this issue to me so I can submit the PR.
Thank you @Tejashri-Taral

**Comment by Sudhanshu248** [comment]
Please assign me. I want to work on it.

**Comment by hars-21** [comment]
You can check issue #70
