### ISSUE TITLE
adding working navbar (as we click on links we can't navigate to that section)

### ISSUE THREAD

**Issue by toshankanwar** [Tejashri-Taral/TrendTrove-Ecommerce#23]
hello @Tejashri-Taral 

i want to add the link navigation functionality in your Navbar as in your project we cant navigate to that particular section .

please give me chance.

Thankyou

**Comment by vararaghu002** [comment]
I'm Interested to work on nav link in your project, pls assign to me.

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than a week, and the website is now updated with new changes
