### ISSUE TITLE
Add Hover Effect to "Quick Links" in Footer

### ISSUE THREAD

**Issue by Shrihari25-hub** [Tejashri-Taral/TrendTrove-Ecommerce#231]
In the footer section of the website, the "Quick Links" are not clearly identifiable as clickable links because they lack a hover effect. This causes confusion for users as it is difficult to distinguish them from regular text.

***********************************************************************************************************************************************
Problem:
The "Quick Links" section currently looks like regular text rather than clickable links.
There is no visual indicator (such as a color change or underline) when hovering over the links.
This can lead to a poor user experience since users might not realize these are links.

***********************************************************************************************************************************************
Name : Shrihari Bhilwadikar
Participant Role : GSSOC, Hacktoberfest 2024

***********************************************************************************************************************************************
I would like to work on this issue. Please assign it to me.

**Comment by Anushka-gupta9** [comment]
I would like to work on this issue. Please assign it to me
