### ISSUE TITLE
Improve Scroll Bar and Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [Tejashri-Taral/TrendTrove-Ecommerce#237]
### Description
The current Scroll bar Ui has a very basic layout and outdated design and site Loading has no preloader. The screen becomes blank when the website loads. Enhancing the colour scheme of Thumb and Track, improving the preloader and modernizing the scroll bar design would greatly improve the user experience and website presentation

### Preloader Mockup 

https://github.com/user-attachments/assets/c7af8434-caff-441d-a733-4a9451ffdf7f

### Tasks:

- Redesign the Scroll bar and preloader for better visual appeal.
- Improving the scroll bar thump and track.
- Improving the preloader.

@Tejashri-Taral  can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by Tejashri-Taral** [comment]
Level will be assign based on work

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me.
