### ISSUE TITLE
heading font

### ISSUE THREAD

**Issue by Assmi0304** [Tejashri-Taral/TrendTrove-Ecommerce#245]
I think the font family and style are quite boring. If you assign me this task, I will do my best to improve and make it more appealing

**Comment by umeshmunde** [comment]
please assign me this as this is not resolved yet. I have good knowledge of frontend development.

**Comment by Assmi0304** [comment]
> please assign me this as this is not resolved yet. I have good knowledge of frontend development.
Dude I m also contributor only
