### ISSUE TITLE
Adding a share & save  button 

### ISSUE THREAD

**Issue by KrishnaMohanty08** [Tejashri-Taral/TrendTrove-Ecommerce#253]
I think these are crucial button to increase influence and traffic for the clothes and trends 
I would like to contribute as making a save button and saved items and adding a share link to every trend card
Could you pls assign me this issue

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by KrishnaMohanty08** [comment]
I made a PR pls check it, and suggest for changes or merge it
