### ISSUE TITLE
Redesigning features section 

### ISSUE THREAD

**Issue by YooAshu** [Tejashri-Taral/TrendTrove-Ecommerce#256]
![Screenshot_2024_1009_103142.jpg](https://github.com/user-attachments/assets/59e513e0-1b0c-4561-bfb4-1889d19afc45)

The feature section does not look good 

assign me for this and I will make it look awesome

**Comment by Tejashri-Taral** [comment]
@YooAshu Go ahead!

**Comment by Tejashri-Taral** [comment]
@YooAshu Can I assign it to someone else?

**Comment by YooAshu** [comment]
Yes
