### ISSUE TITLE
Improving UI of feedback page

### ISSUE THREAD

**Issue by hana-maria** [Tejashri-Taral/TrendTrove-Ecommerce#267]
Would like to improve the UI
<img width="669" alt="Screenshot 2024-10-09 at 8 32 09 PM" src="https://github.com/user-attachments/assets/bf999021-a98d-4366-aa49-7aef7618d59d">
make it something like this, with more enhancements and logo of website 
<img width="481" alt="Screenshot 2024-10-09 at 8 34 06 PM" src="https://github.com/user-attachments/assets/8455558c-3675-4906-be82-f5cfdc2cf68e">

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by hars-21** [comment]
@hana-maria Any Updates?

**Comment by abhishekpanthee** [comment]
can you assign this to me @hars-21

**Comment by hars-21** [comment]
@abhishekpanthee It has already been done. If you wish to propose additional changes please create a new issue
