### ISSUE TITLE
resolve the feedback submit issue and adding a dilogue box to confirm submission

### ISSUE THREAD

**Issue by WednesdaySP** [Tejashri-Taral/TrendTrove-Ecommerce#269]
https://github.com/user-attachments/assets/2a003436-dbb5-4008-8093-7fc8253bfe9e

solution:
1. resolve the issue of page not found and make successful feedback submit
2. Add a dialog box to confirm successful feedback submission.
3. at last navigate the user to the home screen to increase user engagement on the website

I'd like for you to assign me this, and I will fix it.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
It's been more than a week since assigned,as to complete an assigned an medium issue max 3-4 days are enough.
Also someone implemented this already.
You can still raise new issue
