### ISSUE TITLE
BUG:navbar links not working in return policy page

### ISSUE THREAD

**Issue by WednesdaySP** [Tejashri-Taral/TrendTrove-Ecommerce#272]
https://github.com/user-attachments/assets/9ca36fd5-d707-4326-8be8-d39b97f05277

solution:
 linking the nav bar links to their exact locations

@Tejashri-Taral  Assign me this issue, I would like to fix it

**Comment by Tejashri-Taral** [comment]
As this is not a level1 task
I'm giving you one more task - Make navbar like home page

**Comment by WednesdaySP** [comment]
@Tejashri-Taral  sure I'll do it
