### ISSUE TITLE
Adding hover effect to the footer area.

### ISSUE THREAD

**Issue by vijaychandra1910** [Tejashri-Taral/TrendTrove-Ecommerce#274]
Adding some hover effect to footer area  such as about, FAQ,s, Terms and condition etc.  for user interaction 
![Screenshot 2024-10-10 022636](https://github.com/user-attachments/assets/0c0585b6-2a46-42d5-9148-b61ec2165595)

**Comment by Sudhanshu248** [comment]
I have already completed the fix and am just waiting for you to assign this issue to me so I can submit the PR.

**Comment by Tejashri-Taral** [comment]
@Sudhanshu248 Someone is already working on it.
Let's see if he/she not completed then I will assign

**Comment by Sudhanshu248** [comment]
@Tejashri-Taral If no one is working on this issue.
Kindly assign this issue to me. 

Kindly assign this issue to me under the Hacktoberfest'24, Hacktoberfest-accepted, Level-2 label.
