### ISSUE TITLE
Improve Feedback form 

### ISSUE THREAD

**Issue by AfrozeSVU** [Tejashri-Taral/TrendTrove-Ecommerce#276]
I will improve feedback form by adding rate us and adding logo somewhat similar to the refernce given below. 
@Tejashri-Taral Assign me
Iam a contributor at  GSSOC ext and  hacktober

![Screenshot 2024-10-10 075736](https://github.com/user-attachments/assets/c38d8422-704b-4e0d-8048-c91d7bfc4fe9)

![Screenshot 2024-10-10 075249](https://github.com/user-attachments/assets/93912c16-ed4e-4e02-a48b-3112eb6983d4)

**Comment by Tejashri-Taral** [comment]
Any  update?

**Comment by koricherlasupriya** [comment]
ma'am I would like to work on this issue .can you please assign it to me.

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by koricherlasupriya** [comment]
ma'am I would like to work on this issue. can you please assign it to me.
