### ISSUE TITLE
adding a button to scroll up at the top

### ISSUE THREAD

**Issue by ShrishtiSingh26** [Tejashri-Taral/TrendTrove-Ecommerce#28]
we can add a button to scroll up at the top to this and enhance the navigation as well
please assign me this issue under the gssoc-ext and hactoberfest labels

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me under hactoberfest label

**Comment by ShrishtiSingh26** [comment]
@Tejashri-Taral  I have created a PR and resolved the issue #28
Thank you!
