### ISSUE TITLE
Add footer section in your SIGN IN menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [Tejashri-Taral/TrendTrove-Ecommerce#283]
Assign me to make a footer section for your signin menu, which will enhance your UI/UX and help you to mention a good reach for your user. A good footer section is also responsible for branding your company as well as your product. 
So please assign me to make and attach a footer section for your SIGN IN menu.

**Comment by RitikaMaha** [comment]
@sanjay-kv The footer section in this TrendTrove-Ecommerce Website is bit off so I think it can be improved by adding some intresting description

**Comment by Pranjalsinha110** [comment]
footer section along with intresting description is good combination i think
