### ISSUE TITLE
Make Navigation Bar Responsive

### ISSUE THREAD

**Issue by Rahul-AkaVector** [Tejashri-Taral/TrendTrove-Ecommerce#285]
#### The current navigation bar is not responsive, meaning it does not adjust its layout to different screen sizes. This can make it difficult to use on smaller devices like smartphones and tablets.
![image](https://github.com/user-attachments/assets/e7f00bcf-113b-4882-8d65-0769ed6e14b3)

## I believe the navigation bar could be improved by:

- Creating a small left-side dashboard: This would allow users to access the navigation links in a more compact and organized manner.
- Implementing a dropdown menu: This would provide a convenient way to display the navigation links on smaller screens.

@Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
Its been more than a week, are you willing to work on it or should I close the Issue.

**Comment by Rahul-AkaVector** [comment]
Working on the issue. Due to academics, I was just a little busy over the last week.

**Comment by Rahul-AkaVector** [comment]
Hey @Tejashri-Taral ,

I was reviewing the navigation bar code, and I noticed some areas that could use improvement. I’ve proposed a new solution, where I’ve redesigned the entire navbar. This new version retains the essence of the old design but is structured more effectively.


https://github.com/user-attachments/assets/b14071aa-1328-4456-b8e4-80dde67ef527



I plan to implement this navbar into the website with a proper file structure, ensuring it can be reused consistently across the site. What do you think about this approach?

Looking forward to your feedback!

**Comment by hars-21** [comment]
@Rahul-AkaVector Good Idea, You can start working on it. 
One suggestion: In mobile view make the navigation box to full width and incorporate sub product links into the same box (no overlapping).

**Comment by Rahul-AkaVector** [comment]
> @Rahul-AkaVector Good Idea, You can start working on it. One suggestion: In mobile view make the navigation box to full width and incorporate sub product links into the same box (no overlapping).

One suggestion: In mobile view make the navigation box to full width and incorporate sub product links into the same box (no overlapping).

ididnt get this part like exactly which part u want me to avoid overlapping ?

**Comment by hars-21** [comment]
Make this navbar to full width and the sub categories in product (men, women, kids) overlaps the contact us. So fix this.

![image](https://github.com/user-attachments/assets/4ec1e28e-477f-4050-8e4c-87d9765cb426)

**Comment by Tejashri-Taral** [comment]
@Rahul-AkaVector Any update?

**Comment by Tejashri-Taral** [comment]
There is no response so I'm closing this issue.
