### ISSUE TITLE
I want to adjust the navbar for mobile or small screen sizes

### ISSUE THREAD

**Issue by srishti023** [Tejashri-Taral/TrendTrove-Ecommerce#290]
Hi @Tejashri-Taral 
I’ve noticed that **the hamburger menu is currently displaying horizontally, but it should be vertical for better usability.** I would like to take the initiative to fix this issue and work on improving the overall design to enhance user experience.

### How can i Improve this?

**BEFORE IMPROVEMENT:**

https://github.com/user-attachments/assets/df619933-0eaf-4fcb-bf64-1bc82b8221c0

**AFTER IMPROVEMENT:**

https://github.com/user-attachments/assets/d2b5fe72-0ccd-4e5c-b92c-e8c83a26d6fa

**PLease assign me this task with hacktoberfest and gssoc-ext label. I relly wanted to contribute in your project.**

Best regards,
**Srishti**

**Comment by hars-21** [comment]
check #285
