### ISSUE TITLE
There's a spelling mistake under the products label.

### ISSUE THREAD

**Issue by Zubaida0113** [Tejashri-Taral/TrendTrove-Ecommerce#297]
It should be men and women instead of mens and womens. I hope you'll be able to assign this issue to fix.

**Comment by Tejashri-Taral** [comment]
Hi @Zubaida0113 

I'll assign it to you but be sure that I can't add levels to this issues, only gssoc-ext can be given. therefore this PR will reflect on the leaderboard but with no score.

**Comment by Zubaida0113** [comment]
Yeah, sure. No issues with it.
