### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by karu345** [Tejashri-Taral/TrendTrove-Ecommerce#3]
I can add hover effect to about,contact us and others and can do positioning of the icons and can add hover effect on Explore more button.
Please assign this to me.

**Comment by Shetu003** [comment]
Hello Mam, Could you please assign me this issue.

**Comment by karu345** [comment]
@Tejashri-Taral I created this issue please assign this to me.

**Comment by Tejashri-Taral** [comment]
@karu345 Any update?

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than a week, and the website is now updated with new changes
