### ISSUE TITLE
github automatic greeting bot

### ISSUE THREAD

**Issue by reshamsai150** [Tejashri-Taral/TrendTrove-Ecommerce#30]
Adding the automatic greeting bot on raising a issue

**Comment by Tejashri-Taral** [comment]
Can you elaborate How it will work like how it messaged after issue and pr?

**Comment by reshamsai150** [comment]
This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible

**Comment by Tejashri-Taral** [comment]
Proceed!
