### ISSUE TITLE
Add hover effect to navbar

### ISSUE THREAD

**Issue by Antima2004** [Tejashri-Taral/TrendTrove-Ecommerce#31]
Hi,
The current navbar lacks a hover effect, making it less interactive for users. I suggest adding a hover effect that changes the background color or underline when the user hovers over navbar items. This would improve the UI/UX of the navigation bar.

1. Add a hover effect to all navbar links (e.g., color change, underline, or background change).
2. Ensure the effect is smooth and consistent across all screen sizes (desktop and mobile).
3. Test for responsiveness and browser compatibility.

Let me know if I can work on this, or feel free to assign it to me!

**Comment by khushimoon014** [comment]
Can you assign this issue to me

**Comment by Shailjaa30** [comment]
can you assign this issue to me
