### ISSUE TITLE
Enhance UI and adding cursor trail effect

### ISSUE THREAD

**Issue by Piyush01-672** [Tejashri-Taral/TrendTrove-Ecommerce#326]
it needs improvement like its header and footer section, its ARIA roles and proper alignment of brandwears, further adding cursor trail effect.

**Comment by TarunGoel93** [comment]
Here’s a comment you can use to express your interest in working on the UI enhancements and cursor trail effect, along with tagging the maintainer:

Hello! 👋

I’d like to work on enhancing the UI by making some adjustments:

1. I plan to edit the header section to reduce its height for a cleaner look.
2. I also noticed that the footer currently lacks any hover animations. I’ll add hover effects to make the footer more interactive.
3. Additionally, as part of the cursor enhancement, I'll implement a cursor trail effect to improve the overall user experience.
Could you please assign these issues to me? Thanks!

@Tejashri-Taral

**Comment by TarunGoel93** [comment]
Hello! 👋

I’d like to work on enhancing the UI by making some adjustments:

1. I plan to edit the header section to reduce its height for a cleaner look.
2. I also noticed that the footer currently lacks any hover animations. I’ll add hover effects to make the footer more interactive.
3. Additionally, as part of the cursor enhancement, I'll implement a cursor trail effect to improve the overall user experience.
Could you please assign these issues to me? Thanks!

@Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
Work only on the cursor trail effect

**Comment by Piyush01-672** [comment]
@Tejashri-Taral okay , sorry for being late🙏🏻

**Comment by Tejashri-Taral** [comment]
@Piyush01-672 Don't be sorry.It's Ok

**Comment by hars-21** [comment]
@Piyush01-672 Any Updates??

**Comment by Tejashri-Taral** [comment]
its been more than a week since assigned, and after you made the PR it had conflicts, so please make a new PR as soon as possible. Or else I have to close the PR by tomorrow
as to complete an assigned an medium issue max 3-4 days are enough, please take a look into it

**Comment by Piyush01-672** [comment]
@Tejashri-Taral I apologise for it.....I was diagnosed with typhoid so i was not able to do...but i make sure that i will complete in 1-2 days.
Thank you for the cooperation!

**Comment by Tejashri-Taral** [comment]
ok

**Comment by Tejashri-Taral** [comment]
@Piyush01-672
