### ISSUE TITLE
absence of navbar in bags ,sunglasses, and sandles page

### ISSUE THREAD

**Issue by WednesdaySP** [Tejashri-Taral/TrendTrove-Ecommerce#334]
due to absence of navbar in these pages it becomes dificult for user to go back to home page or to any other page.

![image](https://github.com/user-attachments/assets/013300cc-b957-4fd2-b967-4e655716d0e1)

![image](https://github.com/user-attachments/assets/f2c65267-8317-44d7-a23d-79a69860944a)

![image](https://github.com/user-attachments/assets/b1a76ec2-a563-4309-9987-f261f005a674)

**Comment by Tejashri-Taral** [comment]
Add it in all the pages
