### ISSUE TITLE
Fix Contact Page: Submitting Message Shows 'Page Not Working', Implement Success Message Instead

### ISSUE THREAD

**Issue by ragini-gp** [Tejashri-Taral/TrendTrove-Ecommerce#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After submitting the message on Contact Us page, it shows page is not working

![image](https://github.com/user-attachments/assets/6b739e65-4dee-4ca0-926e-cd441fd1b066)
![image](https://github.com/user-attachments/assets/34ab3351-5dc9-4783-890e-ef6758abb83a)

I want to show a message, **"Form submitted successfully**", and then navigate back to Home page.
![image](https://github.com/user-attachments/assets/ec9ea721-eaa2-46cd-940c-8a77a7e2ff69)

@Tejashri-Taral  Please assign me this issue under labels- hacktoberfest-accepeted, gssoc-ext, and appropriate level.

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
you can still find and raise new issues
