### ISSUE TITLE
[Bug]: Product section of mens.

### ISSUE THREAD

**Issue by Prince-1917** [Tejashri-Taral/TrendTrove-Ecommerce#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The tab of mens is not upto industry standard its looking very ugly. Due to add to cart div coming of the side of the grid box making it look ugly

### Add Screenshots / Video Clip

![GSSoc](https://github.com/user-attachments/assets/8686a064-9998-4dea-984e-81f94cac2d91)

### What browsers are you seeing the problem on?

Microsoft Edge

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!
