### ISSUE TITLE
[Bug]: Footer should always be at the bottom of the page irrespective of the height of content above it.

### ISSUE THREAD

**Issue by tarunkumar2005** [Tejashri-Taral/TrendTrove-Ecommerce#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Footer should always be at the bottom of the page irrespective of the height of content above it.

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/5d07b725-ca96-43f4-8eff-a896d8562311)

@Tejashri-Taral Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
you can still find and raise new issue. I am closing this issue. 
thank u
