### ISSUE TITLE
[Feat]: Creating a product page

### ISSUE THREAD

**Issue by tarunkumar2005** [Tejashri-Taral/TrendTrove-Ecommerce#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating a product page means when someone click on a product it will open its desc, price and all the relevent things like in other e commerce website.

### Use Case

Very useful

### Benefits

Very useful

@Tejashri-Taral Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Already implemented
