### ISSUE TITLE
[Feat]: add featured in table in main readme.md file

### ISSUE THREAD

**Issue by tarunkumar2005** [Tejashri-Taral/TrendTrove-Ecommerce#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The task involves updating the main README.md file to include a table highlighting project participation in open source program.

something like this

![image](https://github.com/user-attachments/assets/dd6810c9-58a2-4610-96b4-f397ef5c5829)

@Tejashri-Taral Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Use Case

Very useful

### Benefits

Very useful

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
![WhatsApp Image 2024-10-18 at 16 44 29_461ef25a](https://github.com/user-attachments/assets/8922d1ca-488c-4f27-8653-638ab078a9a0)
![WhatsApp Image 2024-10-18 at 16 45 13_095c067f](https://github.com/user-attachments/assets/5ca5e503-b656-40a1-ae31-e5cf82e952fb)
As this is a documentation issue i am adding extra task  - 
Make this changes in the readme file -  
1. Add featured In GSSOC Extended Program 2024 
2. Add the Table as given in the image below containing repo info

**Comment by Tejashri-Taral** [comment]
![WhatsApp Image 2024-10-18 at 17 03 24_a8d07159](https://github.com/user-attachments/assets/16eb739d-7ec6-4bd9-8b1c-10ddc53dfc40)
Also add contributers page
