### ISSUE TITLE
[Feat]: Improve the UI of navbar and search bar

### ISSUE THREAD

**Issue by Sudhanshu248** [Tejashri-Taral/TrendTrove-Ecommerce#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current navbar UI is not good and also not matching with  the website. Along with this search bar UI is also not good. 

I can improve this. Kindly assign me this issue under the llabel of Hacktoberfest'24 , Hacktoberfest-accepted and level-1.

### Use Case

I think to create it like this :
![Screenshot 2024-10-13 103132](https://github.com/user-attachments/assets/48a64f51-fbf6-4b67-a5bb-903319083ff9)

### Benefits

UI of navbar and search bar will get improves and looks good.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Sudhanshu248** [comment]
Kindly assign me this issue under the label of hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by hars-21** [comment]
I am closing this issue as the given UI doesn't matches the website theme. If you have any other design proposal, please create a new issue.
