### ISSUE TITLE
[Feat]: Make enhancemnt in Website Pages

### ISSUE THREAD

**Issue by MastanSayyad** [Tejashri-Taral/TrendTrove-Ecommerce#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi @Tejashri-Taral 

I would like to make enhancements in your project, such as in home page components and about section images 
can you please assign this issue to me under hacktoberfest?

### Use Case

UI Enhacements

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Any updates?

**Comment by hars-21** [comment]
@MastanSayyad Any Updates??
