### ISSUE TITLE
[Bug]: Add more images of men women and children in landing page

### ISSUE THREAD

**Issue by maniacedoc** [Tejashri-Taral/TrendTrove-Ecommerce#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When opening the landing page, it feels like its a website only for women products, so I want to add more images of both men and women together so that it will give an impression of containing products for every one. 

### Add Screenshots / Video Clip

![Screenshot 2024-10-13 122312](https://github.com/user-attachments/assets/1f33a99c-484f-42ff-b9ed-253556dabe91)
![Screenshot 2024-10-13 122319](https://github.com/user-attachments/assets/0162c952-5a9e-4b72-b396-2cddeb33a46d)
![Screenshot 2024-10-13 122326](https://github.com/user-attachments/assets/5ee48c93-137c-4b68-888e-e1e15f95f946)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by maniacedoc** [comment]
@Tejashri-Taral Please attach the necessary hacktober fest accepted and other labels and assign the issue to me, I want to work on it.

**Comment by Tejashri-Taral** [comment]
Proceed!
