### ISSUE TITLE
[Feat]: Navbar in FAQ's for navigation between pages 

### ISSUE THREAD

**Issue by saumyayadav25** [Tejashri-Taral/TrendTrove-Ecommerce#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On the FAQ's page there is no navbar for navigating back to home or navigating to other pages.
<img width="1277" alt="Screenshot 2024-10-13 at 12 52 05 PM" src="https://github.com/user-attachments/assets/3f77bae5-82fd-4ec2-ba4f-a1d8fc5df89e">

### Use Case

Adding Navbar to FAQ page will improve the user experience and allow them to easy navigate from one section to other. 
If you would not like to add Navbar in FAQ page, just a simple button can be added for navigating back to home page.

Do let me know if the issue is assigned to me. 
Also please tell me whether you would like to add navbar for navigating to different pages of website or just button to get back to home page.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sakshi-nimje** [comment]
Can you assign me this issue?

**Comment by saumyayadav25** [comment]
@Tejashri-Taral kindly review this issue.

**Comment by saumyayadav25** [comment]
@Tejashri-Taral kindly review this issue
