### ISSUE TITLE
[Feat]: button for feedback and enhance ui of feedback page

### ISSUE THREAD

**Issue by ramakandivalasa** [Tejashri-Taral/TrendTrove-Ecommerce#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot 2024-10-13 135038](https://github.com/user-attachments/assets/80aa496a-2d3d-4073-9d2e-a6183e5f431f)
![Screenshot 2024-10-13 135047](https://github.com/user-attachments/assets/82e8e179-77ce-4025-9a92-348d8cdbc935)
i'd like to create a button for feedback option and enhance the feedback page by adding a background and transition effect

### Use Case

have a good  user experience

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
you can still find and raise new issue. I am closing this issue. 
thank u
