### ISSUE TITLE
Irregular `Image Size` And Improper alignment in product pages

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [Tejashri-Taral/TrendTrove-Ecommerce#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Align Images and Button:
- Ensure that all images have a uniform size and aspect ratio.
- Use CSS to align the `Buy Now` buttons with the images.

### Add Padding Around Images:
Add padding to the images to create a more professional appearance.

@Tejashri-Taral please assign me the task

### Add Screenshots / Video Clip

![Screenshot 2024-10-13 173037](https://github.com/user-attachments/assets/43163c12-4e78-4afc-9c29-55ba9abcbc12)

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Adarsh-Chaubey03** [comment]
@Tejashri-Taral please check this out

**Comment by Adarsh-Chaubey03** [comment]
@Tejashri-Taral please assign me this task

**Comment by hars-21** [comment]
@Adarsh-Chaubey03 I am assigning you. Please make these changes in all the product pages.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 I am assigning you. Please make these changes in all the product pages.

Ok
