### ISSUE TITLE
[Feat]: adding chatbot

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Tejashri-Taral/TrendTrove-Ecommerce#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a chat for which will be fine tuned for this website and answer all user queries regarding this website.
@Tejashri-Taral can you please assign me this task.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Phanisirisha-46** [comment]
Hi,
I hope you're doing well. I would love to take on the task of creating an interactive chatbot for our project. I have already developed a sample chatbot UI and would be excited to enhance it further with features like animations and interactivity.

<img width="281" alt="caht" src="https://github.com/user-attachments/assets/546306e8-2d72-4d2e-be28-e4cdc0872239">


Could you please assign this task to me?
Looking forward to your feedback!

Best regards,
Phani Sirisha

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral can you assign me this issue.

**Comment by Tejashri-Taral** [comment]
Currently we don't need this feature to be included
