### ISSUE TITLE
[Feat]: improving contact us page✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Tejashri-Taral/TrendTrove-Ecommerce#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to improve the uI of the contact us page and also add local storage to store user information.
@Tejashri-Taral can you please assign me this task.

### Use Case

<img width="203" alt="Screenshot 2024-10-13 at 8 15 20 PM" src="https://github.com/user-attachments/assets/9f351c03-a72c-4829-b1a6-a83259509f33">

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
Please provide clear description of the changes you are going to make and which part/section will you improve.

**Comment by T-Rahul-prabhu-38** [comment]
ill make the adress cards smaller , the map will be little larger for Ui , ill improve the forms and add storage features for it.
basically ill be following a grid approach.

**Comment by hars-21** [comment]
Proceed!
