### ISSUE TITLE
[Bug]: Remove The anchor tag underline

### ISSUE THREAD

**Issue by 100nuparmar349** [Tejashri-Taral/TrendTrove-Ecommerce#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Home page feedback button there is a exist anchor tag . Remove the underline of anchor tag

### Add Screenshots / Video Clip

![#issue](https://github.com/user-attachments/assets/d9df293e-fb0d-44d6-9761-a875d8f66d06)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.
