### ISSUE TITLE
[Feat]: Adding Hover feature in footer of Website and realigining items/

### ISSUE THREAD

**Issue by PrAyAg9** [Tejashri-Taral/TrendTrove-Ecommerce#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add hover feature on contents of footer in website and align that subscribe button it's too close to input bar when someone hover on it it overwrites the upper section and it doesn't look good.

### Use Case

Hover feature in footer items would look aesthetic.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
This issue is being addressed by someone else. Please look for other issues.
