### ISSUE TITLE
[Feat]: Home Screen Alignment Issues on Screen Resize – Responsiveness Problem

### ISSUE THREAD

**Issue by anurag-026** [Tejashri-Taral/TrendTrove-Ecommerce#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The home screen layout becomes distorted when the screen size is adjusted, causing elements such as images, buttons, and text to lose alignment and proportion. This results in a poor user experience, particularly on devices with varying screen sizes (e.g., tablets and mobile devices).

### Add Screenshots / Video Clip

![Screenshot 2024-10-13 214519](https://github.com/user-attachments/assets/878dff3c-d711-4d58-b6d5-b2c390467f3c)
![Screenshot 2024-10-13 214511](https://github.com/user-attachments/assets/c8c02a7f-5972-418e-bdd5-ab958b349d50)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Any updates?

**Comment by hars-21** [comment]
@anurag-026 Are you working on it? Or should assign it to someone else.

**Comment by Tejashri-Taral** [comment]
It's been more than a week since assigned,as to complete an assigned an medium issue max 3-4 days are enough, please take a look into it.
I have to close the PR by tomorrow. You can still raise new issues
