### ISSUE TITLE
[Bug]: <Heart getting merged with background when hovered>

### ISSUE THREAD

**Issue by jayashisbarua** [Tejashri-Taral/TrendTrove-Ecommerce#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<h2>Description</h2>
When hovering on like icon (heart) its changing it color to white which is getting merged with the background and make its hard for the user to see. Can you please assign this to me under gssoc and hacktoberfest. I would love to contribute in this project. Thank you
<h2>Steps to Reproduce</h2>
I will change the color of like button (heart) to some variant of red color which will fit well with the website.
<h2>Expected Behavior</h2>
like button should be visible by user when hovered.
<h2>Actual Behavior</h2>
Like button's color is changing to white when hovered.
<h2>Browser</h2>
Chrome

### Add Screenshots / Video Clip

<h2>Issue Screenshot</h2>
<img width="1063" alt="Screenshot 2024-10-13 at 9 52 39 PM" src="https://github.com/user-attachments/assets/979e9c09-83ab-4ff3-9997-0a42c96a4470">

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
Proceed!
