### ISSUE TITLE
[Feat]: Adding a Registration/Signin Pop up on Home Page.

### ISSUE THREAD

**Issue by PrAyAg9** [Tejashri-Taral/TrendTrove-Ecommerce#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I think an pop on home screen displaying discount if you sign up for first buy would be really handy for an ecommerce website. I will show you example of what i am talking that would be easy to understand. I am thinking about something like this.
Image:- 
![image](https://github.com/user-attachments/assets/ad075daa-d3f4-4dbf-be27-e72874819d33)

This pop up will come everythime you come to website and you are not logged in. So what do you think.
Assign this issue to me I am sending the pull request.

### Use Case

A discount when you sign in and buy for first time would be really make people sign in to webstie and use it. A win to win deal.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by PrAyAg9** [comment]
I've done the UI design work for pop up, Please suggest if you want different content in it or this is good to go

**Comment by hars-21** [comment]
Proceed!

**Comment by PrAyAg9** [comment]
@hars-21 Done .
