### ISSUE TITLE
Duplication of feedback form

### ISSUE THREAD

**Issue by Kajalmehta29** [Tejashri-Taral/TrendTrove-Ecommerce#385]
<img width="796" alt="Screenshot 2024-10-14 at 12 01 40 AM" src="https://github.com/user-attachments/assets/0b97cbea-4bcc-4f4a-8b07-a5fc7f8e74a1">

<img width="861" alt="Screenshot 2024-10-14 at 12 01 47 AM" src="https://github.com/user-attachments/assets/95a17ebf-a5ca-447c-b5a2-0d0006a6fcea">

Feedback form is made twice. I want to fix this issue.

Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by hars-21** [comment]
This issue has already been fixed
