### ISSUE TITLE
Alignment is not correct.

### ISSUE THREAD

**Issue by Kajalmehta29** [Tejashri-Taral/TrendTrove-Ecommerce#386]
<img width="774" alt="Screenshot 2024-10-14 at 12 03 33 AM" src="https://github.com/user-attachments/assets/8630ca65-a8b3-4d19-8835-7b265062f8d5">

Alignment of given images are not correct. I want to fix this issue.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by harikasayani** [comment]
@Kajalmehta29  you can work on this issue.

**Comment by Kajalmehta29** [comment]
Hey @Tejashri-Taral  @harikasayani  Please add level label too
