### ISSUE TITLE
[Bug]:  Make a page for the Shop clothing 

### ISSUE THREAD

**Issue by itskundanhere** [Tejashri-Taral/TrendTrove-Ecommerce#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to make a shop clothing page and attach to link by which it will open another page and feel free to explore the cloth shopping.

### Add Screenshots / Video Clip

![Screenshot 2024-10-14 012012](https://github.com/user-attachments/assets/61e40ec3-496e-40d5-8207-ee1a70aa2e7b)

make a shopping  page for the cloth shopping to enhance the shopping style.

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by itskundanhere** [comment]
please add the best label for this bug @Tejashri-Taral

**Comment by hars-21** [comment]
Proceed!

**Comment by itskundanhere** [comment]
please add level 2 or 3 label for this work @hars-21

**Comment by hars-21** [comment]
Level Labels will be added based on your work. I'll add the labels once you make the PR
