### ISSUE TITLE
[Feat]: Add Accessories page to the webpage

### ISSUE THREAD

**Issue by Annapoornaaradhya** [Tejashri-Taral/TrendTrove-Ecommerce#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add Accessories section to the website with trendy accessories that users can buy.

### Use Case

It makes very attractive when people can buy the matching and trending accessories along with the clothes.

### Benefits

Attracts more visits to the webpage

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
Proceed!

**Comment by Annapoornaaradhya** [comment]
@hars-21 @Tejashri-Taral I would be grateful if you can please change the level to level 3 in PR #442  as I have taken much efforts to search for the right accessories to match with the theme of the webpage and have created a new feature altogether and added a whole extra page in the website.
Thank you
