### ISSUE TITLE
fix Navbar 

### ISSUE THREAD

**Issue by sahhoArjun097** [Tejashri-Taral/TrendTrove-Ecommerce#4]
I can add hover effect to about,contact us and others and can do positioning of the icons and can add hover effect on Explore more button.
![Screenshot 2024-10-01 182958](https://github.com/user-attachments/assets/1d361e7f-cacc-4fd7-9dd4-8eab974feaaa)
Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant . My GitHub username is [sahhoArjun097](https://github.com/sahhoArjun097).

**Comment by maliumesh1** [comment]
Please assign this issue to me .
https://github.com/maliumesh1
