### ISSUE TITLE
[Feat]: I want to add some Animation

### ISSUE THREAD

**Issue by Mayanksaininh** [Tejashri-Taral/TrendTrove-Ecommerce#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the product section image is static, instead of static these images should be animated after some seconds only those images which products images are present in landing page 
![Screenshot (30)](https://github.com/user-attachments/assets/3efd0b6c-2229-45c4-9ca3-d6edacda1b00)

### Use Case

After adding this feature attraction will be enhanced and look like a branded website.

### Benefits

user  can see the his/her interested product instead of scroll till the end in the page.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
@Mayanksaininh Go ahead

**Comment by Tejashri-Taral** [comment]
Any updates?

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by Mayanksaininh** [comment]
@sunidhi3  I am working on this and already assigned to me

**Comment by Mayanksaininh** [comment]
@Tejashri-Taral Yes i am working

**Comment by hars-21** [comment]
@Mayanksaininh Any Updates? What's the progress

**Comment by Mayanksaininh** [comment]
I have done mens and womens section

**Comment by hars-21** [comment]
okay

**Comment by Tejashri-Taral** [comment]
It's been more than a week since assigned,as to complete an assigned an medium issue max 3-4 days are enough, please take a look into it.
I will wait till tomorrow morning. Otherwise will have to close it.

**Comment by Mayanksaininh** [comment]
Please give me one day after tomorrow

**Comment by Tejashri-Taral** [comment]
Alright! do it asap till sunday morning

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by Mayanksaininh** [comment]
I will generate pr shortly

**Comment by Tejashri-Taral** [comment]
Any update or should I close the issue?

**Comment by Mayanksaininh** [comment]
Please give me only few minutes

**Comment by Tejashri-Taral** [comment]
It's been more than 3 days not few minutes

**Comment by Tejashri-Taral** [comment]
I'llclose this issue by tomorrow

**Comment by rydesert** [comment]
please assign me this issue  with the label gssoc-ext  hacktoberfest  , I am a GSSoC contributor I will complete the task as early as possible .
