### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Aditijainnn** [Tejashri-Taral/TrendTrove-Ecommerce#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/7b574192-e628-4a36-bf96-8c9b30ceef46)
in login page there is  no option of going back to home without signing in so adding that

### Use Case

assign this to me under gssoc ext

### Priority

Medium

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
This issue already exists.
