### ISSUE TITLE
[Feat]: Update README File

### ISSUE THREAD

**Issue by neeru24** [Tejashri-Taral/TrendTrove-Ecommerce#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The README file needs an update to enhance its clarity, usability, and overall presentation. This update will include improved formatting, visual elements, and additional information to better guide users and contributors.

### Proposed Changes:

- Screenshots 📸:

Add screenshots showcasing key features of the application to provide a visual reference.

- Animations 🎨:

Include GIFs or videos demonstrating key interactions and animations within the application for better engagement.

- Improved Readability 📝:

Refactor content to use clear and concise language.
Use bullet points and headers to improve navigation.

- Contributor Pictures 👥:

Add images or avatars of contributors to personalize the section and highlight team efforts.

- Table Metrics 📊:

Create a table to show number of PRS, stars, forks etc.

### Benefits

- Enhances user engagement and understanding of the application.
- Attracts more contributors by showcasing team efforts and a friendly environment.
- Provides a clearer overview of features and their advantages, making it easier for new users to get started.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Already assigned to someone

**Comment by neeru24** [comment]
> Already assigned to someone

Can you assign to me too? I'll submit a PR soon and will include all the necessary things
