### ISSUE TITLE
[Feat]: adding language translator

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Tejashri-Taral/TrendTrove-Ecommerce#418]
### Is there an existing issue for this?
- [X] I have searched the existing issues

### Feature Description
i want to add language translator which will promote multi language support for the website.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral can you assign me this task please

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral can u assign me this aswell.

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral can u assign me this aswell.

**Comment by Tejashri-Taral** [comment]
Currently we don't need this feature to be included. you can still raise and find new issues
