### ISSUE TITLE
Scroll to top button availability

### ISSUE THREAD

**Issue by Devanshu1603** [Tejashri-Taral/TrendTrove-Ecommerce#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Scroll to top button is not available on many pages .

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Devanshu1603** [comment]
@Tejashri-Taral  please assign me this issue under gssoc-extended , hacktober fest accepted will be happy to work.

**Comment by hars-21** [comment]
Go ahead!

**Comment by hars-21** [comment]
@Devanshu1603 Please make your PR.

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by Tejashri-Taral** [comment]
@Devanshu1603 Please make a new pr asap by tomorrow's evening else I'll close this

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
Any updates?

**Comment by Tejashri-Taral** [comment]
It's been more than a week and website is updated
I'm closing this issue because scroll to top button present now
