### ISSUE TITLE
[Bug]:  Kids Section

### ISSUE THREAD

**Issue by itskundanhere** [Tejashri-Taral/TrendTrove-Ecommerce#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Spelling of the Kid is wrong its Kids Section.

### Add Screenshots / Video Clip

![Screenshot 2024-10-15 011209](https://github.com/user-attachments/assets/138f5631-567a-4afd-9ee9-1965f3c1e069)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by itskundanhere** [comment]
@Tejashri-Taral  please assign for this work

**Comment by Tejashri-Taral** [comment]
@itskundanhere I'll assign it to you but be sure that I can't add levels to this issues, only gssoc-ext can be given. therefore this PR will reflect on the leaderboard but with no score.

**Comment by itskundanhere** [comment]
@Tejashri-Taral add atleast any label by which i can increase my score
