### ISSUE TITLE
[Bug]: Sign Up and Login functionality not working

### ISSUE THREAD

**Issue by Nagesh-tri** [Tejashri-Taral/TrendTrove-Ecommerce#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Login and signup features are not working,  It only logs that login/sign up success but actually not doing anything.
I looked up for the functionality but in page there was no such code that implement it.
I may add these functionalities and also maintaining the users and their data by adding database and authentication using JWT.
with proper documentation how is done.
assign me this issue, with proper lebels

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/4e348604-9f40-4247-81e5-4cb4e1d6ad79)
![image](https://github.com/user-attachments/assets/63909afb-5d19-4452-83e3-8104c216957e)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
t's been more than a week since assigned,as to complete an assigned an medium issue max 3-4 days are enough, please take a look into it.
I have to close the PR by tomorrow. You can still raise new issues
