### ISSUE TITLE
[Feat]: animation in nav-button

### ISSUE THREAD

**Issue by anilgadhe** [Tejashri-Taral/TrendTrove-Ecommerce#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

by using animation in nav buttons it will enhance the look of nav buttons

### Use Case

it will definatly satisfying feature for the users

### Benefits

enhance the over-all look of nav buttons

### Priority

Medium

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [x] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
@anilgadhe Warning!! Please don't create multiple same issues. #426
