### ISSUE TITLE
[Feat]: UI of features Section.

### ISSUE THREAD

**Issue by Rish6392** [Tejashri-Taral/TrendTrove-Ecommerce#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to change the css of features section to make it look attractive.

![Uploading Screenshot 2024-10-15 112118.png…]()

### Use Case

it will make it more beautiful.

### Benefits

it will give the website a better look.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Rish6392** [comment]
![Screenshot 2024-10-15 112118](https://github.com/user-attachments/assets/5c3d6ded-09c2-41a7-9b53-1f3a0098f886)
i want to make the UI of feature section attractive.
please assign this issue to me @Tejashri-Taral .

**Comment by Tejashri-Taral** [comment]
@Rish6392 Please make sure to follow the website theme
