### ISSUE TITLE
[Feat]: Alignment of the icons in the navbar

### ISSUE THREAD

**Issue by shriyadindi** [Tejashri-Taral/TrendTrove-Ecommerce#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to align the icons in the navbar properly for a better and impressive user interface, kindly assign me the task.

### Use Case

This feature would enhance the user interface.
![Screenshot 2024-10-15 120522](https://github.com/user-attachments/assets/8d51a802-4c5a-4eac-b6a4-b3b48eaf26ba)

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by laxmishvhegde** [comment]
please assign this task to me. I am ready

**Comment by 100nuparmar349** [comment]
#assign please

**Comment by Tejashri-Taral** [comment]
you can still find and raise new issues.
