### ISSUE TITLE
[Bug]: Contact Page Not Responsive

### ISSUE THREAD

**Issue by Amankr200** [Tejashri-Taral/TrendTrove-Ecommerce#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Contact Page Not Responsive  @Tejashri-Taral make it level 3

### Add Screenshots / Video Clip

 

https://github.com/user-attachments/assets/0ef8aa70-854f-4e41-9fcc-b6d769447bc0

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Level will be assigned based on the work
