### ISSUE TITLE
[Bug]: Overflow in contact page

### ISSUE THREAD

**Issue by Gauravtb2253** [Tejashri-Taral/TrendTrove-Ecommerce#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is horizontal scrolling happening in contact page

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/c44a37da-c34b-434f-b76b-036b155dca0a)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Hey @Gauravtb2253 Someone already made changes 
You can find new issues
