### ISSUE TITLE
 Add Frequently Asked Questions (FAQ) Section to the Website

### ISSUE THREAD

**Issue by Subham1** [Tejashri-Taral/TrendTrove-Ecommerce#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to suggest the addition of a "Frequently Asked Questions (FAQ)" section to the website. The FAQ section can address common user inquiries and provide answers to key questions about the website's features, usage, security, and troubleshooting. This would streamline user support and reduce repetitive queries.

### Use Case

This feature would enhance the project by providing users with quick, self-service answers to common questions without needing to contact support or navigate through multiple pages. It can cover topics like:

1.Security measures
2.Troubleshooting common issues
3.User guidelines
An FAQ section would improve user experience by offering a centralized source of information.

### Benefits

-> It would reduce the load on customer support by providing answers to common queries.
-> It would improve user retention by quickly resolving potential user confusion.
-> It adds professionalism to the website and shows commitment to providing comprehensive support.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subham1** [comment]
As this feature request is raised as part of GSSoC Extend '24, could you please assign the gssoc ext label to this issue

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor
