### ISSUE TITLE
Navbar icon issue 

### ISSUE THREAD

**Issue by dipeshkumar799** [Tejashri-Taral/TrendTrove-Ecommerce#440]
while hover on shop icon there  showing  pointer  and i want to add whiler hover to show there cursor and the size will inrease and also this issue in search icon.
the next issue is  while we scroll page  the navbar gonna hidden   that also i fixed it.
![Screenshot (70)](https://github.com/user-attachments/assets/33853332-c7d7-49a0-93c6-1f2a77f039fb)

@Tejashri-Taral :plse assign me .

**Comment by hars-21** [comment]
@dipeshkumar799 Any updates??

**Comment by Tejashri-Taral** [comment]
@dipeshkumar799 It's been more than a week.Please take a look
Otherwise I'll close this issue by tomorrow

**Comment by dipeshkumar799** [comment]
U have to closed already I don't know when u have to open this
