### ISSUE TITLE
[Feat]: Add to cart functionality

### ISSUE THREAD

**Issue by aditya07389** [Tejashri-Taral/TrendTrove-Ecommerce#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add an add to cart button  with each product for users to add to cart
![image](https://github.com/user-attachments/assets/a6928cee-a890-4de6-b037-b09124f66b5a)

### Use Case

users can add desired products to cart

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by aditya07389** [comment]
hey @harikasayani , i just noticed someone has already added the add to cart button , so i would like to add the functionality to this , upon clicking on add to cart , it will add it and also show in the cart popover and also show number of items in the cart like for ex :(3)

**Comment by aditya07389** [comment]
should i proceed with this work ?

**Comment by aditya07389** [comment]
Okay cool, thanks

**Comment by hars-21** [comment]
@aditya07389 Any Updates ?? It's been a week.

**Comment by aditya07389** [comment]
Hey, I am really sorry, I have been caught up with some work, you could assign the issue to someone else :(
