### ISSUE TITLE
[Bug]: Issue in styling of navbar

### ISSUE THREAD

**Issue by swarraaa** [Tejashri-Taral/TrendTrove-Ecommerce#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the left and right elements of the navbar are hovered, the black background of these elements touches the border of the navbar. It needs to be fixed by adding proper margin,

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/9c113929-9c5c-4540-9c99-9c6261d8c855)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by swarraaa** [comment]
@Tejashri-Taral Could you pls take a look and assign me the issue?

**Comment by Tejashri-Taral** [comment]
Navbar is already good
