### ISSUE TITLE
[Bug]:  Product page Kid section , Enhance the UI of the feature section and contact us Page overflow.

### ISSUE THREAD

**Issue by Deepankar1484** [Tejashri-Taral/TrendTrove-Ecommerce#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. The feature section UI is very naive and basic, So making it a little awesome.
2. Contact us page has a map which is getting out of the page.
3. when we are at the home page and go for the products their shows a Kid section but when visited to about us page it disappears in product dropdown. 

### Add Screenshots / Video Clip

**Navbar Product bug**
<img width="751" alt="Screenshot 2024-10-15 at 11 14 49 PM" src="https://github.com/user-attachments/assets/bdd9f503-dc0f-40e3-9b10-f6331a301397">
<img width="752" alt="Screenshot 2024-10-15 at 11 15 05 PM" src="https://github.com/user-attachments/assets/9d6cd341-9208-4c22-b881-06647c410495">
**Contact us page**
<img width="1512" alt="Screenshot 2024-10-15 at 11 15 28 PM" src="https://github.com/user-attachments/assets/2974c42e-1db3-408c-95b8-521b2a8eb336">
**Features Page**
<img width="1512" alt="Screenshot 2024-10-15 at 11 15 43 PM" src="https://github.com/user-attachments/assets/5730864f-f618-4cd8-8eca-34e880f83327">

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
you can still raise and find new issues
