### ISSUE TITLE
[Feat]: Make Discount Coupon Popup Work and Appear Only Once Per Session

### ISSUE THREAD

**Issue by krishashah-03** [Tejashri-Taral/TrendTrove-Ecommerce#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The discount popup currently reappears every time a user revisits the home page and the form's "Continue" button does not process the email correctly. This enhancement will address two issues:

Coupon Popup Logic: Ensure the popup appears only once per session using sessionStorage. Once the popup is closed or the user submits their email, it should not appear again until a new session.
Working Form Submission: When the user enters their email and clicks "Continue," the form should validate the email and apply the coupon. Upon successful submission, the popup will display a confirmation message

### Use Case

This feature would improve the user experience by:

Preventing the popup from appearing multiple times, which can frustrate users.
Ensuring the "Continue" button processes the user's email and applies the coupon.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by harshini1807** [comment]
may i work on this
