### ISSUE TITLE
adding hovering effect to the logo of shopping basket .

### ISSUE THREAD

**Issue by Tanushree084** [Tejashri-Taral/TrendTrove-Ecommerce#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hey @Tejashri-Taral ,
i want to add hovering effect to the shopping basket .
currently it is :
<img width="74" alt="image" src="https://github.com/user-attachments/assets/b6e3fa29-273d-43f6-909d-3871e830baff">
 can you please assign me this issue ?

### Use Case

it will add more effect to the website .

### Benefits

.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
@Tanushree084 someone is already working on it.
