### ISSUE TITLE
Improve plain text design on the features page

### ISSUE THREAD

**Issue by Subham1** [Tejashri-Taral/TrendTrove-Ecommerce#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The content on the  features page (User-Experience, Seamless Integration, Security Measures) is displayed in plain text. This plain design doesn’t match the stylish, visually appealing nature of the clothing shopping website. It looks simple and doesn’t align with the website’s theme

### Add Screenshots / Video Clip

The information is shown in basic text with no clear visual separation. It would be more attractive and user-friendly if the content was organized into corresponding cards that look visually appealing and fit with the overall design of the shopping website.

![image](https://github.com/user-attachments/assets/cfe2ae90-0707-4af8-81f9-8ccef2ac34ec)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subham1** [comment]
@Tejashri-Taral  could you  pls assign this work i will work on it

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.
