### ISSUE TITLE
Adding some animations to the shop now icons

### ISSUE THREAD

**Issue by hannah-maria** [Tejashri-Taral/TrendTrove-Ecommerce#48]
- I would like to add some animations to these icons
- example) if i hover over it, it'll become a different colour as it looks very plain right now
consider assigning me this isssue with labels gssoc ext, and hactoberfest :)

<img width="1469" alt="Screenshot 2024-10-02 at 4 02 48 PM" src="https://github.com/user-attachments/assets/739f3c94-0712-4ad4-98d4-d268bd7b670d">

**Comment by Tejashri-Taral** [comment]
It's been more than 3 week since assigned,as to complete an assigned an medium issue max 3-4 days are enough, please take a look into it.
I have to close this. You can still raise new issues
