### ISSUE TITLE
[Feat]: The Add to Cart Button is not working

### ISSUE THREAD

**Issue by Siddhart2004** [Tejashri-Taral/TrendTrove-Ecommerce#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Description:**  
The "Add to Cart" button is not functioning as expected, preventing users from adding items to their cart. This feature aims to resolve the issue and ensure the button works seamlessly across all relevant pages.

### Use Case

- A user visits the product page and decides to purchase a product. They click the "Add to Cart" button, expecting the product to be added to their cart.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Siddhart2004** [comment]
@Tejashri-Taral Assign this task to me and kindly add relevant labels.

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.
