### ISSUE TITLE
[Feat]: Add Cookie Pop-up to the Website

### ISSUE THREAD

**Issue by sanikamandale17** [Tejashri-Taral/TrendTrove-Ecommerce#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to Add Cookie Pop-up to the Website, included the paragraph to understand the concept.
It is responsive too

### Use Case

this feature will help keep users informed about cookies and allow them to manage their preferences ensuring a more transparent and user-friendly experience

### Benefits

builds user trust by offering clear cookie options.
works smoothly across devices.
comopliance with privacy laws 

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Currently we don't need this feature to be included. you can still raise and find new issues
