### ISSUE TITLE
[Bug]: header is not responsive

### ISSUE THREAD

**Issue by siddhant-2002** [Tejashri-Taral/TrendTrove-Ecommerce#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 header is not responsive

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.

**Comment by Tejashri-Taral** [comment]
someone is already working on it.you can still find and raise new issues
