### ISSUE TITLE
[Bug]: About us page doesnot show all the products

### ISSUE THREAD

**Issue by poojitha-ch** [Tejashri-Taral/TrendTrove-Ecommerce#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the products in the navbar doesnot show kidsection and accessories.

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/0b170236-59c2-4a82-b1d2-393eee4c4a95)
<br>
I want to work on this issue.
Please assign me this issue under gssoc-extd,hacktoberfest-accepted and appropriate level.
@Tejashri-Taral @hars-21 @BrindaManani

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
We want to keep the about us page simple. hence we didn't add this info. 
you can still find and raise new issue
