### ISSUE TITLE
Fixing alignment of Input and Subscribe Button

### ISSUE THREAD

**Issue by ParasY1724** [Tejashri-Taral/TrendTrove-Ecommerce#5]
**Description:**
Fixing alignment of Input and Subscribe Button.
Screenshot:
![Screenshot From 2024-10-01 18-32-32](https://github.com/user-attachments/assets/63c94c4c-1899-4e3d-96ec-ca6f9188f943)

**Comment by ParasY1724** [comment]
Please assign this task to me under gssoc-ext24

**Comment by maliumesh1** [comment]
Please assign this issue to me .
https://github.com/maliumesh1

**Comment by MadhavDhatrak** [comment]
Hi there!

I noticed this issue is already assigned, but I had a solution ready and submitted a PR #33  Feel free to review or close it if it’s not needed.

Thanks!


![Screenshot (428)](https://github.com/user-attachments/assets/1a97c33e-be3f-470e-96fd-299bc8406453)

**Comment by ParasY1724** [comment]
> Hi there!
> 
> I noticed this issue is already assigned, but I had a solution ready and submitted a PR #33  Feel free to review or close it if it’s not needed.
> 
> Thanks!
> 
> 
> ![Screenshot (428)](https://github.com/user-attachments/assets/1a97c33e-be3f-470e-96fd-299bc8406453)
> 

I had already submitted PR 13h ago  for review.Once its merge Project Admin will close this issue.

Also you are allowed to raised PR for assigned issues only according to guidelines pf gssoc
