### ISSUE TITLE
[Bug]: feature page and dropdowns

### ISSUE THREAD

**Issue by siddhant-2002** [Tejashri-Taral/TrendTrove-Ecommerce#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

feature page and its dropdowns are very simple I want to make it stylish and look good

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/7bed8f62-80f1-47a9-b71d-456488487ae0)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
someone is already working on it.you can still find and raise new issues
