### ISSUE TITLE
[Bug]: styling and positionning of middle box is not good

### ISSUE THREAD

**Issue by siddhant-2002** [Tejashri-Taral/TrendTrove-Ecommerce#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

styling and positionning of middle box is not good

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/2e9dd914-6990-4945-bae1-4d22f750af46)

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by Tejashri-Taral** [comment]
Please elaborate @siddhant-2002
