### ISSUE TITLE
Improving UI design of Home page

### ISSUE THREAD

**Issue by Pushpa472** [Tejashri-Taral/TrendTrove-Ecommerce#503]
@Tejashri-Taral  To enhance the visual appeal of the homepage, we should focus on improving the UI design by incorporating a modern layout, vibrant color schemes, and intuitive navigation elements and also to enhance header and footer section.
please assign me and add labels
![image](https://github.com/user-attachments/assets/8863f362-a6af-43c8-b19d-81eddf47fb3f)
![image](https://github.com/user-attachments/assets/473f857a-b087-4b96-be6a-cdcbabdf2815)

**Comment by Tejashri-Taral** [comment]
someone recently improved it. you can still find and raise new issues
