### ISSUE TITLE
[Bug]: Quick links are working

### ISSUE THREAD

**Issue by Mayanksaininh** [Tejashri-Taral/TrendTrove-Ecommerce#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Quick links are not working and buttons also have not landing page.

### Add Screenshots / Video Clip

![Screenshot (52)](https://github.com/user-attachments/assets/14a01632-336a-4136-8b8d-2ca814bd96d5)

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ishivansmishra** [comment]
@Mayanksaininh please assign me this issue under the hacktoberfest , gssoc ext  and appropriate level
