### ISSUE TITLE
[Feat]: Redesign Contact Us Form

### ISSUE THREAD

**Issue by Gurpreet0022** [Tejashri-Taral/TrendTrove-Ecommerce#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the contact us page , form is excessively large . It feels like it is spread on the entire screen . 
![Screenshot (157)](https://github.com/user-attachments/assets/f132f480-bd32-4358-bffe-447215e8955d)

### Use Case

Enhnces UI

### Benefits

looks appealing and friendly

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Gurpreet0022** [comment]
Could you assign me this task under `gssoc extd`,'`level` ,`hacktoberfest` and `hacktoberfest-accepted` labels ?

**Comment by Tejashri-Taral** [comment]
@Gurpreet0022 Contact form updated

**Comment by Gurpreet0022** [comment]
@Tejashri-Taral , have you done with this ? Or you are assigning me this task ? Please clear your message .
