### ISSUE TITLE
[Bug]:  Hover Effect on accessories page is not working

### ISSUE THREAD

**Issue by VidhanThakur09** [Tejashri-Taral/TrendTrove-Ecommerce#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 
The hover effect on the accessories page items is not working properly. Improving hover effect on items would greatly improve the user experience and website presentation

### Describe the solution you'd like

- Apply hover effect items on accessories page.
- Improving the hover effects on each item. 

@Tejashri-Taral can you assign this issue to me with labels "gssoc-ext" with levels,"hacktoberfest-accepted";

### Add Screenshots / Video Clip

Problem

https://github.com/user-attachments/assets/c12e5751-f08e-45ee-a729-3e30c2a2b713

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by VidhanThakur09** [comment]
@Tejashri-Taral I would greatly appreciate it if you could check this issue.

**Comment by VidhanThakur09** [comment]
@Tejashri-Taral It would be greatly appreciated if you could kindly review this Issue.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me
