### ISSUE TITLE
Proposal to add "Products showcase page with respective categories"

### ISSUE THREAD

**Issue by clownfish1805** [Tejashri-Taral/TrendTrove-Ecommerce#51]
@Tejashri-Taral I would like to add Products showcase page for the website TrendTrove e-com site.
My plan:

This page will display a wide range of products, organized into categories, with product images, descriptions, and prices. 

**Key features:**

1. **Grid layout** for product images and descriptions.
2. Categories **filter for easier navigation.**
3. **Add-to-cart** functionality for each product.
4. **Responsive design** to ensure usability across different devices.

This feature will enhance the shopping experience by providing a visually appealing and functional way for customers to view and purchase products.

**Comment by clownfish1805** [comment]
@Tejashri-Taral  Please assign me this issue under **hacktoberfest and GSSOC'24** extended with level labels.

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than 10days, and the website is now updated with new changes
