### ISSUE TITLE
[Feat]: Hover effects on the whole pages 

### ISSUE THREAD

**Issue by aditiverma-21** [Tejashri-Taral/TrendTrove-Ecommerce#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/5b07272b-612e-4f3a-a3f6-8acf1545217d)
![image](https://github.com/user-attachments/assets/27cb9f4c-409a-489e-84a5-5c093e993570)
![image](https://github.com/user-attachments/assets/a72ea527-c886-44c5-88eb-787cf0aeed1e)
![image](https://github.com/user-attachments/assets/c88d1cf9-6422-4b1c-9a90-133222dc7836)

Adding the hover effects to all these sections 

### Use Case

The features enhances the UI of the website

### Benefits

Transitional effects

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor
