### ISSUE TITLE
[Bug]: Navbar hover effect

### ISSUE THREAD

**Issue by Bhum-ika** [Tejashri-Taral/TrendTrove-Ecommerce#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicked on Home, the effect is really not looking good.
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.
I will fix in the best way

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/6c18cbf1-9a07-46c9-9fab-8533e30338f6)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Vanshika-OFFICIAL** [comment]
kindly assign it to me.

**Comment by Tejashri-Taral** [comment]
The navbar is already have GSAP animation effects . you can still find and raise new issues
