### ISSUE TITLE
[Feat]: ENHANCEMENT OF THE USER INTERFACE OF THE FEEDBACK SECTION✨

### ISSUE THREAD

**Issue by shriyadindi** [Tejashri-Taral/TrendTrove-Ecommerce#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to do the enhancment of the css styling of the feedback section.

### Use Case

CSS styling and UI enhancement

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
someone is already working on it. you can still find and raise new issues
Thank u
