### ISSUE TITLE
Search bar, Cart and Profile page

### ISSUE THREAD

**Issue by S7viks** [Tejashri-Taral/TrendTrove-Ecommerce#52]
Willing to add a functional search bar, My cart page and Profile page

![image](https://github.com/user-attachments/assets/3f2fea47-67b1-4baf-8e86-41b29eb2055d)

Please add Gssoc-extended labels along with level tags

**Comment by S7viks** [comment]
@Tejashri-Taral please add level 3 label to this

**Comment by S7viks** [comment]
@Tejashri-Taral @Gauravtb2253 @saras-69 @yeshwanth-ds please assign level label to this

**Comment by hars-21** [comment]
Hey @S7viks Please proceed with the task. Level labels will be assigned once you create PR based on your contribution.

**Comment by S7viks** [comment]
Okay

**Comment by S7viks** [comment]
Please check, Ive merged with my fork. also assign level label and you can close issue #52

**Comment by Tejashri-Taral** [comment]
You made a PR in your fork repository You should make it in my repo

**Comment by S7viks** [comment]
Hi, sorry for that, Please check the updated branch.

**Comment by hars-21** [comment]
@S7viks Any Updates?? It's been a week. Please respond asap.

**Comment by S7viks** [comment]
@hars-21 please check, I've re-committed my changes.
