### ISSUE TITLE
[Feat]:  Clicking outside body of popup should also close it.

### ISSUE THREAD

**Issue by PrAyAg9** [Tejashri-Taral/TrendTrove-Ecommerce#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I suppose some people will find it hard to close the pop up or find irritating and most of them try clicking outside to close it. So for better user experience should we add this feature that if we click outside the body of pop up it will disapper automatically. 

### Use Case

if we click outside the body of pop up it will disappear automatically. 

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by BhavikaPachauri** [comment]
assign me the task under GSSOC AND HACKTOBERFEST .
