### ISSUE TITLE
[Feat]: Add a rating and feedback form 

### ISSUE THREAD

**Issue by maniacedoc** [Tejashri-Taral/TrendTrove-Ecommerce#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a form under the contact us section where customers can provide their valuable feedback to us. 

### Use Case

This will help us better our website and the products. It is very important for the owner to know what is the particular thing that their customer is liking and this will help us enhance the reach!

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
the feedback form already exists In the website ...you can still find and raise new issues
