### ISSUE TITLE
[Feat]: Bot for automatic thank you response on PR merge 

### ISSUE THREAD

**Issue by maniacedoc** [Tejashri-Taral/TrendTrove-Ecommerce#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This github bot will automatically respond giving a thankyou note for the merging of PR.

### Use Case

This will motivate our contributors to keep doing the good work and also save time of the project admin to individually comment on each pr after merging them.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
@maniacedoc  as this contribution comes under documentation . I cant give further level for this task. I can merge the PR with only gssoc label. 
you will not get any points for it. Hope you understand - please let me know if you want to work on it.
