### ISSUE TITLE
Change in CSS of banner section

### ISSUE THREAD

**Issue by aakanshimalik** [Tejashri-Taral/TrendTrove-Ecommerce#526]
Enhancement in the margins of  h1,p,button. As originally it is somewhat overlapping with the image in banner section.
@Tejashri-Taral please assign this task to me.

output:
![image](https://github.com/user-attachments/assets/dd9f26fd-8653-4df5-bc61-dcb51cb6a798)

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it

**Comment by hars-21** [comment]
@aakanshimalik Please make this section responsive as well. I am assigning it to you.
