### ISSUE TITLE
[Feat]: Want to make navbar sticky

### ISSUE THREAD

**Issue by Gaurav075** [Tejashri-Taral/TrendTrove-Ecommerce#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to make the navbar sticky so that even after scrolling down we will be able to see the navbar.
![Screenshot (359)](https://github.com/user-attachments/assets/2d23a513-712f-4400-a55f-5d9154a532a3)
![Screenshot (360)](https://github.com/user-attachments/assets/fda5bd88-4eb6-41a4-b3ff-ea9f05d42648)

### Use Case

It will increase the user experience.

### Benefits

user experience

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Nadha6240** [comment]
Please assign this to me i can work on it

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it
