### ISSUE TITLE
[Feat]: Active Nav Links effect

### ISSUE THREAD

**Issue by Rohit72099** [Tejashri-Taral/TrendTrove-Ecommerce#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we move to a page , navbar menu should show which page is active, but its not happening on any page.

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/fd67b7c6-4465-4d42-b47b-e47f48b85d55)

![image](https://github.com/user-attachments/assets/1406bdd6-ef46-48ca-90cb-6906ac6f6eb5)

![image](https://github.com/user-attachments/assets/e13eb0e7-c89e-4d64-9f39-bfca3880e5d1)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sona30k** [comment]
I would like to work on this issue please assign it to me

**Comment by hars-21** [comment]
Proceed!

**Comment by Rohit72099** [comment]
but i raise this issue you should it me

**Comment by hars-21** [comment]
Done

**Comment by Tejashri-Taral** [comment]
@Rohit72099 Any update?

**Comment by Rohit72099** [comment]
Submit by tomorrow

**Comment by Tejashri-Taral** [comment]
@Rohit72099 Should I close this?

**Comment by Rohit72099** [comment]
Plz No , 
due to exam I become late
But I will complete it by Tuesday
