### ISSUE TITLE
Improve Footer Layout by adjusting button spacing for better layout and adding more features.

### ISSUE THREAD

**Issue by Orca-63** [Tejashri-Taral/TrendTrove-Ecommerce#54]
I would like to add the following features to the footer : 

1) Improve Footer Layout by Adjusting Button Spacing for Better Layout.
2) Including copyright information.
3) Adding hover effects for each social media icons.

![Screenshot 2024-10-02 191001](https://github.com/user-attachments/assets/c2c47c2b-1e27-45f1-b650-ab6fd7432f72)

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than 10 days, and the website is now updated with new changes
