### ISSUE TITLE
[Bug]: "Login/Signup /Account ,Search and bucket functionality not working on about and contact pages"

### ISSUE THREAD

**Issue by Kasaksaxena** [Tejashri-Taral/TrendTrove-Ecommerce#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login/signup and search/bucket functionalities are not operational on the About and Contact Us pages of the website. 

When navigating to the About or Contact Us pages, users see the login/signup and search options, but they do not respond when clicked. The expected behavior is that the login/signup button should redirect users to the login page, and the search/bucket option should allow users to access their cart or search products.

Steps to reproduce the issue:
1. Navigate to the About page.
2. Click on the login/signup button.
3. Observe that nothing happens.

 the buttons are unresponsive.

### Add Screenshots / Video Clip

![issue 1](https://github.com/user-attachments/assets/4a1945de-32ae-4dbc-be2c-c6ed1f949706)
![issue 2](https://github.com/user-attachments/assets/b03c653c-0cb0-46ab-aa21-b0f7256a5ef8)

NOT RESPONDING!!

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Snehamanded** [comment]
I would like to work on this issue please  assign it to me
