### ISSUE TITLE
[Feat]:  Add a Cart Page 

### ISSUE THREAD

**Issue by AfrozeSVU** [Tejashri-Taral/TrendTrove-Ecommerce#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a Cart Page when the cart icon in NAvbar is clicked. 
![Screenshot 2024-10-18 224758](https://github.com/user-attachments/assets/259c6ac9-0a07-4987-b955-13c0db92e4bf)
 This is the Basic UI I will improve the page . 

@Tejashri-Taral  assign me the issue

### Use Case

The Customers Can easily  make a note of their liked Clothing

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by supreetkaursareen** [comment]
@AfrozeSVU can you assign it to me?
