### ISSUE TITLE
[Feat]: PRIVACY POLICY page for the website is MISSING 

### ISSUE THREAD

**Issue by KAUSHIKRM-36** [Tejashri-Taral/TrendTrove-Ecommerce#547]
A new privacy policy page is needed for the website to inform users about how their personal data will be collected, used, and protected. This page should clearly outline the types of information collected, user rights, data sharing practices, and compliance with applicable data protection laws. Establishing this page is crucial for enhancing transparency and building user trust, ensuring that customers are aware of their privacy rights while using our services.

@Tejashri-Taral ,  please assign me this task under 

GSSOC-extd 24
Hacktoberfest24
at level 3

**Comment by hars-21** [comment]
Proceed!

**Comment by KAUSHIKRM-36** [comment]
@hars-21 please add the level 3 tag

**Comment by hars-21** [comment]
@KAUSHIKRM-36 Level will be assigned based on your work.

**Comment by KAUSHIKRM-36** [comment]
@hars-21 and  @Tejashri-Taral    
 please review and approve the PR
-  #578

**Comment by KAUSHIKRM-36** [comment]
@Tejashri-Taral please review the PR
