### ISSUE TITLE
[Feat]: Add Password Pattern Validation

### ISSUE THREAD

**Issue by DevyanshiS** [Tejashri-Taral/TrendTrove-Ecommerce#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature will implement a password pattern for validation, ensuring the user enters a password that meets security standards. The pattern will include requirements like a minimum length, uppercase and lowercase letters, and numbers.

### Use Case

This feature enhances security by ensuring users create strong, complex passwords.

### Benefits

1. stronger user passwords
2. Improved security for the project.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task
