### ISSUE TITLE
[Bug]: it can't responsive

### ISSUE THREAD

**Issue by PayalSathawane** [Tejashri-Taral/TrendTrove-Ecommerce#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

making responsive it

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sunidhi3** [comment]
hey assign me this issue.

**Comment by hars-21** [comment]
First of all, Please describe your issue and correct the title. No one can understand what is the issue.

**Comment by ambrishgoswami** [comment]
hey assign me this issue.
