### ISSUE TITLE
[Feat]: ENHANCING THE ACCESSORIES PRODUCTS SAME LIKE OTHER PAGES

### ISSUE THREAD

**Issue by laxmikandivalasa** [Tejashri-Taral/TrendTrove-Ecommerce#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot (289)](https://github.com/user-attachments/assets/f9fd1408-d8d5-48f7-98f1-6f0451764c0a)
all the products in men, women and kids section are in one alignment and design
where as this accessories products does not align to this style...
I'd like to enhance them to the better style along with the add to cart button

### Use Case

This would have great user experience

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by laxmikandivalasa** [comment]
![image](https://github.com/user-attachments/assets/7ea4f1d8-18d3-417f-a7fb-3085b0b8cd1e)
@harikasayani 
@Tejashri-Taral
While committing  changes I'm getting this way
can you help me with this??

**Comment by laxmikandivalasa** [comment]
hello can you respond?? 
@Tejashri-Taral 
@harikasayani 
I've done done all  the changes to the pages but committing changes is raising a error!

**Comment by hars-21** [comment]
Hey @laxmikandivalasa You cannot directly push commits to this repo, first you have to fork this repo, clone it into your system then push commits in your forked repo, and then create a PR.

**Comment by Tejashri-Taral** [comment]
@laxmikandivalasa you can push commit directly to repo and then make a pr
