### ISSUE TITLE
The enhancement of sign up and login page 

### ISSUE THREAD

**Issue by Lekkhasri** [Tejashri-Taral/TrendTrove-Ecommerce#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The sign up and login page can be enhanced by adding the password conditions like adding uppercase, lowercase, special characters. 
Continue with google , Github, twitter option for user friendly usage.
![image](https://github.com/user-attachments/assets/64e8403f-1eba-458c-8738-37e0916e26e1)
![image](https://github.com/user-attachments/assets/66b2eb56-ebe4-4825-8499-f1d23579fcb0)

### Use Case

It looks a complete outlook to the webpage .

### Benefits

The user can have more advantages with this features.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AADESHak007** [comment]
@Lekkhasri  if you are not working on this issue then I would like to work on this .
Please notify

**Comment by Lekkhasri** [comment]
@AADESHak007 I am working on this issue I will complete it today night

**Comment by AADESHak007** [comment]
> Any update? or should I assign it to someone else will be waiting till tomorrow morning @AADESHak007 tag me tomorrow

Surely , Thank you

**Comment by Lekkhasri** [comment]
@Tejashri-Taral sorry I am having exams I can't complete the work you can assign the work to @AADESHak007

**Comment by hars-21** [comment]
@AADESHak007 You can start working on it.

**Comment by AADESHak007** [comment]
> @AADESHak007 You can start working on it.

Sure .
