### ISSUE TITLE
[Feat]: About Us Page

### ISSUE THREAD

**Issue by BVaishnavi15** [Tejashri-Taral/TrendTrove-Ecommerce#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to enhance the about us page. 

### Use Case

It enhances the Website

### Benefits

Better information  can be provided with the about us page 

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by harikasayani** [comment]
@BVaishnavi15 can you please share some sample screenshots or briefly explain about it.

**Comment by BVaishnavi15** [comment]
Adding "Our mission" "Our Vision" "Why choose us" "Our team" Sections.
