### ISSUE TITLE
Adding Hover Effect to Explore More Button

### ISSUE THREAD

**Issue by ahinagangopadhyay** [Tejashri-Taral/TrendTrove-Ecommerce#58]
![Screenshot (245)](https://github.com/user-attachments/assets/cad1e7f7-5111-43d6-8d2c-4867b4668765)
I want to add a hover effect to the Explore more button and impove the ui of the page.
Please assign me this issue for Hacktoberfest 2024

**Comment by khushiiagrawal** [comment]
hey can you assign this to me under hacktoberfest
