### ISSUE TITLE
[Bug]: footer is not properly aligned 

### ISSUE THREAD

**Issue by Theboycut05** [Tejashri-Taral/TrendTrove-Ecommerce#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I checked this website the footer was improperly located at the bottom making it unable to read clearly 

### Add Screenshots / Video Clip

![Screenshot_20241020_090106](https://github.com/user-attachments/assets/2462a544-2d70-4955-bcf9-42d1eb5c5acb)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [x] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!
