### ISSUE TITLE
[Feat]: Add a close button to the pop-up page.

### ISSUE THREAD

**Issue by madhumitha-b** [Tejashri-Taral/TrendTrove-Ecommerce#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Problem: The pop-up page currently does not have a close button.

![Screenshot 2024-10-20 095802](https://github.com/user-attachments/assets/bfac8934-2b78-4527-900a-7b7da2ac425a)

### Use Case

Adding a close button will enhance the user experience by allowing users to easily dismiss the pop-up, and navigate through the page without any interruption.

### Benefits

Adding a close button to the pop-up page will enhance the user experience by allowing users to easily dismiss the pop-up. This will make the interface more user-friendly, reduce frustration, and improve overall site navigation. It also aligns with common web design practices, ensuring consistency and familiarity for users.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sameer-soni** [comment]
Can I get assigned to this?
