### ISSUE TITLE
 Extend FAQs Section for Improved Buyer Communication

### ISSUE THREAD

**Issue by sriharsha0x1** [Tejashri-Taral/TrendTrove-Ecommerce#590]
I noticed that the current FAQ section contains only four questions. To address more common customer inquiries and ensure better communication, I recommend expanding this section. Customers are looking for more clarification, and providing additional FAQs can help clear their doubts effectively.

Could you please assign this task to me? @Tejashri-Taral

![image](https://github.com/user-attachments/assets/b4624ab5-3385-40de-b466-c8e2f6bb21fb)

**Comment by Tejashri-Taral** [comment]
Proceed!
