### ISSUE TITLE
Add Footer for Sneaker Shop Page

### ISSUE THREAD

**Issue by sriharsha0x1** [Tejashri-Taral/TrendTrove-Ecommerce#592]
I noticed that the sneaker shop page currently lacks a footer section, which is important for maintaining consistency across the site and providing key information for customers. I would like to take on the task of adding a proper footer to this page.

Could you please assign this task to me? @Tejashri-Taral 
![image](https://github.com/user-attachments/assets/a9e97538-516d-40cd-b91f-0f52f555b714)

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
It's been more than 2 weeks 
Program will end tomorrow I'm closing this issue.
