### ISSUE TITLE
Adjust Filter Box Sizes for Better UI

### ISSUE THREAD

**Issue by sriharsha0x1** [Tejashri-Taral/TrendTrove-Ecommerce#593]
I noticed that the size of the filter boxes (for brand, price range, and size) on the product page is quite large, which disrupts the overall user experience. I believe resizing them would enhance the page's appearance and make it more user-friendly.

Could you please assign this task to me? @Tejashri-Taral 
![image](https://github.com/user-attachments/assets/2e861ef8-8c4e-4469-a888-0991cc709859)

**Comment by hars-21** [comment]
@sriharsha0x1 Proceed!

**Comment by sriharsha0x1** [comment]
@hars-21  please add level tag too..!
