### ISSUE TITLE
[Feat]: the text at home page should have animation to it to make website effective !

### ISSUE THREAD

**Issue by 2004pra** [Tejashri-Taral/TrendTrove-Ecommerce#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the feature is basically to provide animation to the text at the home page using some gradient colors 
please assign this issue atleast level 2 , gssoc , hactoberfest accepted too
right now it looks like this --->
![Screenshot 2024-10-20 161437](https://github.com/user-attachments/assets/1cb2c92f-a0ba-4126-ba87-41926f1e1a29)

### Use Case

it will make the website more engaging and intuitive !

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by harikasayani** [comment]
@2004pra  can you share sample video?

**Comment by 2004pra** [comment]
It will be available today at 10  pm because of Diwali I am a bit busy
please don’t give the issue to someone else please ..

**Comment by 2004pra** [comment]
so it will be something like this you can see ...

https://github.com/user-attachments/assets/b8bd4fc7-4ea9-492c-8990-1f25e7e3a74e

**Comment by 2004pra** [comment]
there are other samples too but if you assign me  i can show you the preview after providing the animation
