### ISSUE TITLE
[Feat]: Convert images to webp format

### ISSUE THREAD

**Issue by Gauravtb2253** [Tejashri-Taral/TrendTrove-Ecommerce#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to change images to webp format

### Use Case

Webp images are faster to load and offer optimization

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by nigam-divyanshi-dev** [comment]
please assign this issue to me under gssoc or hacktoberfest . thankyou .

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task
