### ISSUE TITLE
Fixing Navbar for mobile view

### ISSUE THREAD

**Issue by ParasY1724** [Tejashri-Taral/TrendTrove-Ecommerce#6]
**Description:**
On mobile view the hamburg navbar when expanded shows icons overflowed.
Screenshoot:
![Screenshot From 2024-10-01 18-35-57](https://github.com/user-attachments/assets/9abc46f3-6af3-4461-b6b1-2ef23d16c3eb)

**Comment by ParasY1724** [comment]
Please assign this task to me under gssoc-ext24

**Comment by maliumesh1** [comment]
Please assign this issue to me .
https://github.com/maliumesh1

**Comment by ParasY1724** [comment]
@Tejashri-Taral this is implemented with previous PR i had mentioned it.
PR NO : #18 
Before:
![Screenshot From 2024-10-01 18-35-57](https://github.com/user-attachments/assets/1bc9d1ef-46c3-4805-8ed5-d52d447c144a)
After:
![MobileView](https://github.com/user-attachments/assets/35a08ef1-17f8-432f-bbfe-95e261adfef9)
