### ISSUE TITLE
SO many grammatical mistakes on feedback pge

### ISSUE THREAD

**Issue by Kajalmehta29** [Tejashri-Taral/TrendTrove-Ecommerce#600]
There are many grammatical mistakes in the feedback page. Also i want to add the "star us" option on the feedback page.

Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by singh-shreya27** [comment]
There are many grammatical mistakes in the feedback page and it is also very boring. I can make the feedback interface more attractive and beneficial by adding some more options like 
 why is the user leaving, 
 how would they rate us with the help of different emoticons and 
 based on their experience would they recommend us to their family and friends and
 some more options like these also.
It will look somewhat like this:
![Screenshot 2024-10-20 191639](https://github.com/user-attachments/assets/2bb11e84-b594-445f-8eaa-6e6daa54810a)

@Tejashri-Taral 
Please assign me this issue under gssoc extended and hacktoberfest accepted. I can work on this issue .
