### ISSUE TITLE
[Bug]: Miss Placement of icon in footer 

### ISSUE THREAD

**Issue by aashutosh585** [Tejashri-Taral/TrendTrove-Ecommerce#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an issue with the alignment or placement of more icons in the footer section of the website. The social media or external link icons do not align as expected, which disrupts the overall design and user experience.

### Add Screenshots / Video Clip

![Screenshot 2024-10-20 203750](https://github.com/user-attachments/assets/b0be9177-2215-42b4-85a0-3948e379260d)

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by aashutosh585** [comment]
@harikasayani  please add appropriate level ( level1, level2, level3 ) also.

**Comment by Tejashri-Taral** [comment]
Level will be assigned based on your work
