### ISSUE TITLE
[Feat]: Add a star rating widget ⭐

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Tejashri-Taral/TrendTrove-Ecommerce#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a star rating widget in Feedback section. That will make this website more beautiful.

PA @te please assign me this task.

![Screenshot 2024-10-20 213319](https://github.com/user-attachments/assets/91aace30-71ee-452c-ba0e-13d843806dcf)

### Use Case

..

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subhajit-2023-44** [comment]
@Tejashri-Taral

**Comment by hars-21** [comment]
@Subhajit-2023-44 Warning!! Don't create multiple duplicate issues. If you are seen next time repeating this, you'll have to face consequences.
