### ISSUE TITLE
[Feat]: Hover effect on card in Accessories not working

### ISSUE THREAD

**Issue by aashutosh585** [Tejashri-Taral/TrendTrove-Ecommerce#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Tejashri-Taral ,Hover effect very badly used on Accessories page. little more enhancement on that page  and footer. So if you assign me then I make it more better and user-friendly also.

https://github.com/user-attachments/assets/b7ab209c-4d7d-4920-a6ad-f225a3bf9499

and Please make sure to add labels gssoc-ext, hactoberfest, level1, level2, level3.

### Use Case

To highlight the currently hovered menu item in a navbar or dropdown.

### Benefits

Enhanced User Interaction, Improved Visual Feedback, Increased Accessibility

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
It's been more than a week I'm closing this issue no response from your side
