### ISSUE TITLE
Add functionality

### ISSUE THREAD

**Issue by shivamy009** [Tejashri-Taral/TrendTrove-Ecommerce#61]
![Screenshot 2024-10-02 215346](https://github.com/user-attachments/assets/b9d8e638-95e8-43b5-b692-2b3da0b6b0f6)
Add here functionality if user don't have account

Please assign me to fix this

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than 10 days, and the website is now updated with new changes
