### ISSUE TITLE
[Bug]: Some UI fixes 

### ISSUE THREAD

**Issue by pbln** [Tejashri-Taral/TrendTrove-Ecommerce#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The font-family written with the images is not consistent with the overall font family and it looks a bit odd. Please assign this to me to fix it under hacktoberfest and gssoc-ext. 

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/f28eb70e-2aee-4b55-8ab9-173ee75899ed)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by technoKC** [comment]
![Screenshot 2024-10-27 194043](https://github.com/user-attachments/assets/5dc3b8b0-baab-4202-a391-ef76c244aa13)
This section of UI needs to be enhanced and looks attracting, some more accessories need to be added and the responsiveness should be improved. Please assign this to me to fix it under gssoc-ext.

**Comment by pbln** [comment]
@technoKC I have already raised an issue for this but this task hasn't been assigned yet .

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by pbln** [comment]
![image](https://github.com/user-attachments/assets/b05ae2de-2fd0-4e6f-9434-8ee6d112df61)
I have added some scroll animation , and also fixed the font-family , What else do you expect?
