### ISSUE TITLE
[Bug]: Need of Fixed Navbar

### ISSUE THREAD

**Issue by pbln** [Tejashri-Taral/TrendTrove-Ecommerce#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we scroll down and want to access the profile or check the cart , we have to go the top again which is really a bug , i think the navbar should remain fixed with scrolling . Please assign this task to me . Thank you .

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/30d48465-bc7c-4007-850f-a1c136369086)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!
