### ISSUE TITLE
[Feat]: loyalty reward system

### ISSUE THREAD

**Issue by harshini1807** [Tejashri-Taral/TrendTrove-Ecommerce#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

a royalty program can be Introduced  where users can earn points on purchases and redeem them for discounts or gifts

### Use Case

it would allow for users to maek more purchases for discounts/

### Benefits

Enhanced User Interaction and  Feedback, 

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task
