### ISSUE TITLE
[Bug]: Changed the file name of login-sginup to signup with all the links changes to the correct one

### ISSUE THREAD

**Issue by harjasae2001** [Tejashri-Taral/TrendTrove-Ecommerce#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an incorrect html page name for login-sginup. So I corrected it and changed all the links wherever necessary.
![{8EF43C35-E409-4FCA-B2FF-7AE703A66005}](https://github.com/user-attachments/assets/d2037f7e-4061-42d5-a1a4-df3c98a8e511)

I have already solved the issue so pls assign this issue to me so that i can pull the PR

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [x] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by harjasae2001** [comment]
@Tejashri-Taral pls assign this issue

**Comment by harjasae2001** [comment]
@harikasayani pls assign me this issue

**Comment by harjasae2001** [comment]
@Tejashri-Taral pls assign me this issue.

**Comment by harjasae2001** [comment]
I have already made the changes just need to publish a PR.

**Comment by harjasae2001** [comment]
@hars-21 pls assign me this issue. I really want to contribute.

**Comment by hars-21** [comment]
@harjasae2001 Hey, the issue you have opened is irrelevant. You can search existing issues or create a new one.
