### ISSUE TITLE
[Bug]: kid section and accessories not visible under products after switching to any page except home

### ISSUE THREAD

**Issue by anshxika** [Tejashri-Taral/TrendTrove-Ecommerce#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when i look from the home page i see there are 4 product types but after switching to any of the tab through navbar , it shows only two products (missing kid section and accessories)

(@harikasayani please assign me this issue, i'll fix it as quick as possible)

### Add Screenshots / Video Clip

here is how it looks at home page: 
![Screenshot 2024-10-22 062515](https://github.com/user-attachments/assets/ba3c5cbb-45b3-4142-8110-1f90a7eb711b)

and this is how at other pages: 
![Screenshot 2024-10-22 062300](https://github.com/user-attachments/assets/b41bacb8-15d7-479e-863e-0b9fe0209e33)
![Screenshot 2024-10-22 062308](https://github.com/user-attachments/assets/d67023b6-dd64-425b-b24f-16f0abfe6817)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
@anshxika Proceed!

**Comment by anshxika** [comment]
@hars-21 thankyou and the PR is done from my side for this bug :)
(added the sections where-ever they were missing)
