### ISSUE TITLE
[Feat]:  Improve Terms and Conditions Page ✔

### ISSUE THREAD

**Issue by iarmaanx** [Tejashri-Taral/TrendTrove-Ecommerce#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

**Title:** Improve Terms and Conditions Page

**Type of Issue:** Content Improvement

**Description:**  
The current Terms and Conditions page lacks clarity and readability, making it difficult for users to understand the information presented. Enhancing the layout and language will improve user experience and comprehension.

### Use Case

**Proposed Solution:**  
I can restructure the content, use clearer language, and implement a more organized layout for the Terms and Conditions page, making it easier for users to navigate and understand the terms.

**Labels Request:**  
Please add the following labels: `gssoc`, `hacktoberfest`, and `level`.

**Screenshot:**  
![Screenshot (2)](https://github.com/user-attachments/assets/02440c7c-8b8c-42d9-b0b6-9164006728ba)

### Priority

Low

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by iarmaanx** [comment]
I would love to work on this issue. Consider assigning this to me.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
Any update?
