### ISSUE TITLE
[Feat]: Improve Return and Refund Policy Page with Card-Based UI

### ISSUE THREAD

**Issue by neeru24** [Tejashri-Taral/TrendTrove-Ecommerce#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue: Improve Return and Refund Policy Page with Card-Based UI

**Description:**  
The current Return and Refund Policy page can be difficult to navigate due to its static layout and text-heavy format. To make it more user-friendly, the page can be redesigned using a card-based layout to break down sections and improve readability.

**Goals:**
- Implement a card-based design to better organize the content and enhance user experience.

**Expected Improvements:**
1. **Card-Based Layout:**
   - Divide the policy into individual cards for sections like "Eligibility for Return," "Refund Process," "Exceptions," and "Contact Information."
   
2. **Visual Design:**
   - Use cards with subtle shadow and hover effects to create a more engaging and interactive experience.

3. **Typography:**
   - Improve the readability by adjusting font size, line spacing, and section headings within each card.

4. **Icons and Visual Cues:**
   - Add icons or visual cues in each card to make key information easier to identify.

5. **Responsive Design:**
   - Ensure that the card layout is fully responsive and works well on all screen sizes.

**Proposed Solutions:**
- Redesign the page with a card-based UI for each section of the policy.
- Use CSS to style the cards, adding hover effects and proper spacing for better navigation.
- Ensure the page is optimized for both desktop and mobile users.

### Use Case

![image](https://github.com/user-attachments/assets/2ef83ae6-aaa9-497d-9f7c-5e847e907dc3)

### Benefits

This card-based design will help users quickly find the information they need, improving the overall usability of the Return and Refund Policy page.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!
