### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [Tejashri-Taral/TrendTrove-Ecommerce#633]
Issue Description
adding Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

![2024-10-22 (11)](https://github.com/user-attachments/assets/f8d5f931-f027-40ff-878c-d867ed17e136)

**Comment by amiya-cyber** [comment]
please @Tejashri-Taral assign me this issue and add all the labels
hacktoberfest
gssoc
level 2 or level 3

**Comment by amiya-cyber** [comment]
please @Tejashri-Taral assign me so that i can work immediately and add all the labels
gssoc ext
hacktoberfest
level 2 or level 3

**Comment by Tejashri-Taral** [comment]
Proceed!
Level will be increased based on ur work
