### ISSUE TITLE
[Feat]: Designing Feedback Form Page and Adding Navbar and Footer to it.

### ISSUE THREAD

**Issue by Baig-fatema** [Tejashri-Taral/TrendTrove-Ecommerce#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Designing Feedback Form Page and Adding Navbar and Footer to it.**

1. Making the Feedback Form more Responsive and adding Styling to it.
2. Adding Navbar and Footer For Page Navigation.
3. Customizing input fields in Form.

### Use Case

1. giving user customize view of form.
2. its easy for user to interact with form.
3. giving them the Page navigation features by adding navbar and footer to the Feedback form page

### Benefits

1. User Interaction will be increase.
2. More Feedback will given by user.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Baig-fatema** [comment]
**Initial Feedback Form without Responsive ness and Navbar and Footer:**
![Screenshot (100)](https://github.com/user-attachments/assets/32b25246-18eb-42b6-9587-23753bc981cf)

**Comment by Baig-fatema** [comment]
@Tejashri-Taral I am Requesting you to please Assign this task to me.
Add following Labels:

- gssoc
- gssoc-extd
- gssoc-2024
- hacker to be fest
- Level2

**Comment by Tejashri-Taral** [comment]
Please make a new PR

**Comment by Baig-fatema** [comment]
@Tejashri-Taral  as per your above comment i have made new PR, i request you to please review it and merge it.
add my points to leader boar.
