### ISSUE TITLE
Improving overall responsiveness

### ISSUE THREAD

**Issue by shivhere007** [Tejashri-Taral/TrendTrove-Ecommerce#647]
The current layout and elements of the page need to be optimized for mobile devices.
I would like to improve the responsiveness of the page , as there are many little irregularities present.
![Screenshot 2024-10-24 010722](https://github.com/user-attachments/assets/0bb0ad5b-0fe2-40c6-b896-2c81c3ea0108)
![Screenshot 2024-10-24 010742](https://github.com/user-attachments/assets/f7941f26-21dd-4512-89bb-faa7de0773a8)

The mobile responsiveness of the navigation bar needs attention to improve usability on smaller screens.
![Screenshot 2024-10-24 010759](https://github.com/user-attachments/assets/521941fe-2f6d-415d-a438-9959c40d0763)

Do assign it to me @Tejashri-Taral @hars-21 , I would like to work on it.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by Tejashri-Taral** [comment]
No response from your side so I'm closing this issue
