### ISSUE TITLE
[Bug]: Container Height

### ISSUE THREAD

**Issue by 100nuparmar349** [Tejashri-Taral/TrendTrove-Ecommerce#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This container image not take  equal height of all the image every  image take differnt height so i want to improve this bug 
please assign me this  isssue
![#isse4](https://github.com/user-attachments/assets/2b703bd5-0852-45df-b08f-2a83e8c8125e)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by arpit74170** [comment]
Please assign this task to me @Tejashri-Taral

**Comment by Vaishnavishinde9552** [comment]
Please assign this task to me
