### ISSUE TITLE
[Feat]:Update README to Include Contribution Guidelines

### ISSUE THREAD

**Issue by riyaa060** [Tejashri-Taral/TrendTrove-Ecommerce#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current README file does not provide sufficient guidance on how to contribute to the project. This can be particularly challenging for beginners who may not be familiar with open-source contributions or Git workflows. 
![Screenshot 2024-10-24 112617](https://github.com/user-attachments/assets/8b412466-2560-4973-b12e-4cc446757835)

### Use Case

Clear, step-by-step instructions will help newcomers navigate the process and encourage their participation.

### Benefits

Adding clear guidelines will help potential contributors understand the process and encourage more participation.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
@riyaa060 Contributing.md already exists.

**Comment by riyaa060** [comment]
Okay
