### ISSUE TITLE
[Bug]: feedback form is not there

### ISSUE THREAD

**Issue by SandhyaBadwaik** [Tejashri-Taral/TrendTrove-Ecommerce#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

issue : after shopping there must be feedback form for the user to know the overall experience of the user after using this website or application
proposition : can add the button of feedback form to get the overall experience of the user.

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by harikasayani** [comment]
@SandhyaBadwaik
feedback form already exists in project.
