### ISSUE TITLE
[Feat]: Returning to home page!

### ISSUE THREAD

**Issue by devanshigit** [Tejashri-Taral/TrendTrove-Ecommerce#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Upon clicking the logo of the website, it should return to the home page but currently it has no response on click.

### Use Case

Usually, people tend to click the logo for home screen (in personal experience) as many UIs use this feature.

### Priority

Medium

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hars-21** [comment]
@devanshigit This feature already exists.
