### ISSUE TITLE
[Bug]: Issues with the Cart!

### ISSUE THREAD

**Issue by devanshigit** [Tejashri-Taral/TrendTrove-Ecommerce#658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cannot add or remove a particular product. The quantity is not visible either. Also, there is no total being displayed at the checkout. 

### Add Screenshots / Video Clip

[

https://github.com/user-attachments/assets/0428a6f4-e290-40ce-a29f-b6f52a385cb6

](url)

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [ ] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by devanshigit** [comment]
Did not realise that the screen recording was not proper, here is the proper one!

https://github.com/user-attachments/assets/88e76ebb-e0ca-4b2b-9247-9af047ff19a6

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by rishika105** [comment]
Please assign me this issue.

**Comment by Tejashri-Taral** [comment]
Any update?
