### ISSUE TITLE
[Bug]: Share window is disaligned

### ISSUE THREAD

**Issue by hars-21** [Tejashri-Taral/TrendTrove-Ecommerce#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the products page, under women category when we click on share for any product the share window pops on hero section which should not be the case. 

Fix share window - To be only visible on product. 
Improve share popup ui

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/08af2b3c-9ebe-458e-812f-c748d742d8b6)

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [ ] I want to work on this issue [Optional]
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by anshxika** [comment]
its coming like this (same is for the kids section ) :

![Screenshot 2024-10-25 223944](https://github.com/user-attachments/assets/0734f074-aea7-4646-88b6-565d49f4f1e4)
  
on the men and accessories section the pop up window doesn't appear at all on clicking share
i could make the popup show over the boundary of the card and not get chopped like that. I would love to help on it.

**Comment by hars-21** [comment]
Okay, make sure it is responsive as well. Also, add to every product page.
