### ISSUE TITLE
[Bug]: Pop up close button not working

### ISSUE THREAD

**Issue by daky2024** [Tejashri-Taral/TrendTrove-Ecommerce#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

hello !!! @Tejashri-Taral , I have searched the bug related to pop up cookie
The close button is not visible in the pop-up cookie  . I would like to fix the issue . please assign me this issue under **hacktoberfest** , **Gssoc'24 extnd ** and level as you wish.

### Add Screenshots / Video Clip

![Screenshot_26-10-2024_103258_github com](https://github.com/user-attachments/assets/85ffb938-fedb-45a7-a7b4-a89d01480f4f)

### What browsers are you seeing the problem on?

Microsoft Edge

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by daky2024** [comment]
Hello @Tejashri-Taral please assign me this issue . Under hacktoberfest , GSsoc'24 and level as you wish.

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task

**Comment by BhavikaPachauri** [comment]
assign me the task under GSSOC AND HACKTOBERFEST .
