### ISSUE TITLE
Add top scroll button on every page

### ISSUE THREAD

**Issue by rutikakengal** [Tejashri-Taral/TrendTrove-Ecommerce#668]
As In website Top scroll button in home page and features and contact page only , in remaining pages like About and product page is not there and in that men and women page there is not scroll button 
@Tejashri-Taral Assign me I like to work on it , Add gssoc -ext and hactoberfest accepted and level to this issue

**Comment by 2004pra** [comment]
please assign me this issue as i have mostly updated other projects scroll to top button
@Tejashri-Taral  under gssoc extd , hactoberfest
