### ISSUE TITLE
Improve SEO by Optimizing Meta Description, Keywords and Title Tag.

### ISSUE THREAD

**Issue by Pragyaa3** [Tejashri-Taral/TrendTrove-Ecommerce#67]
**Aim:**
Adding Meta Description, Keywords and enhancing Title Tag for SEO Optimization.

**Description:**
To improve the website’s SEO and search engine visibility, I propose adding the following elements to the <head> section of each HTML page:

1)Meta Description: This will help users understand the page content when it appears in search results.

2)Meta Keywords:  This will help in targeting niche or specific keyword searches.

3)Title Tag: This will improve the page's visibility on search engines, attract a wider audience, and ensure the title reflects the brand and its offerings.

**Do I Want To Work On This**
- [x] Yes
- [ ] No

**Kindly mark this under GSSoC'24-EXTD**

**Comment by Tejashri-Taral** [comment]
I appreciate your contributions! However, according to the extended GSSoC guidelines, direct pull requests should not be made without first raising an issue and getting assigned to it.

Unfortunately, I can't merge PRs that haven't followed this protocol, so please make sure to raise an issue, get it assigned, and then proceed with your PR. 
Thank you for your understanding and cooperation!
