### ISSUE TITLE
🌟Feature: Add a Scroll Progress Indicator Bar!

### ISSUE THREAD

**Issue by aslams2020** [Tejashri-Taral/TrendTrove-Ecommerce#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Tejashri-Taral 
I want to add a **"Scroll Down Progress Bar"**

Example Like this - 
As All the "component pages" are Large for scrolling, this Scroll Progress Bar Will Definitely Improve the user's scrolling experience and will also help to know their location on the page -

![image](https://github.com/XceeDesigns/Website/assets/131389695/0f92f30d-9dd7-464f-b1fb-6e854d1fe01c)

PLEASE ASSIGN THIS TO ME UNDER **Hactoberfest'24** 

### Use Case

.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!
