### ISSUE TITLE
[Feat]: Adding favicon to the website

### ISSUE THREAD

**Issue by AyutheCoder** [Tejashri-Taral/TrendTrove-Ecommerce#675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Favicon to website

### Use Case

It will enhance the website

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AyutheCoder** [comment]
@Tejashri-Taral Kindly review the issue and assign to me.

**Comment by AyutheCoder** [comment]
@Tejashri-Taral ,Kindly review the issue and assign this task to me.

**Comment by Tejashri-Taral** [comment]
It's already present
