### ISSUE TITLE
[Feat]:  Add to cart button not functioning properly

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [Tejashri-Taral/TrendTrove-Ecommerce#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Add to Cart" button for products is currently non-functional, preventing users from adding selected items to their shopping cart.

Steps to Reproduce:

Navigate to the product page of any item.
Click on the "Add to Cart" button.
Observe that the item does not appear in the shopping cart.

### Use Case

The "Add to Cart" feature enhances the project by providing a seamless shopping experience, allowing users to easily compile and manage their selected products. This functionality increases user engagement and satisfaction, potentially leading to higher conversion rates and repeat visits. Additionally, it facilitates better inventory management and supports promotional campaigns.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Pallavi-Mukalla** [comment]
@Tejashri-Taral please assign me this issue

**Comment by Pallavi-Mukalla** [comment]
@Tejashri-Taral please assign me this issue

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task

**Comment by Tejashri-Taral** [comment]
Proceed!
