### ISSUE TITLE
[Bug]: Non-Functional 'Explore' Button on the Home Page

### ISSUE THREAD

**Issue by Chitrakadyan2005** [Tejashri-Taral/TrendTrove-Ecommerce#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The 'Explore' button on the home page is currently non-functional. When clicked, it does not navigate the user to the intended section or page. This issue affects the user experience by creating confusion and preventing users from exploring the available features or content that the button should lead to.

please assign me this issue under GSSOC'24EXTD , hacktoberfest'24 and level labels @Tejashri-Taral .

### Add Screenshots / Video Clip

https://github.com/user-attachments/assets/6c8ed887-d6c2-4803-8c47-d7d83313c44c

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by Chitrakadyan2005** [comment]
@Tejashri-Taral 
sorry for the late reply I am busy cause my exams are going on according to what you said do you want me to create another page for the button to direct to, if not please tell me which page you would like me to direct it to.

**Comment by Tejashri-Taral** [comment]
Yes
