### ISSUE TITLE
Redesigning contact us page

### ISSUE THREAD

**Issue by Subashree-selvaraj** [Tejashri-Taral/TrendTrove-Ecommerce#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We would like to enhance the "Contact Us" page to improve user experience and align it with the overall aesthetic of the TrendTrove platform. The new design should be modern, intuitive, and responsive across all devices.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subashree-selvaraj** [comment]
I have raised the issue solve kindly assign it to me

**Comment by Tejashri-Taral** [comment]
@Subashree-selvaraj What's your plan?
Any screenshots how u are going to design?
