### ISSUE TITLE
enhanced the home page 

### ISSUE THREAD

**Issue by priyashuu** [Tejashri-Taral/TrendTrove-Ecommerce#69]
Objective: I propose enhancing the navbar like this
https://github.com/user-attachments/assets/f6aabd48-4bda-4905-856a-362cd43cd31d
2nd objective :I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

Details:

Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback

**Comment by khushiiagrawal** [comment]
hey, can you assign me this under hacktoberfest

**Comment by Akanshaku** [comment]
I would like to work on it pls assign me this under GSSoC'24 Extd.

**Comment by SHUBHAG100520** [comment]
Can i also work on the project .

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by priyashuu** [comment]
ya i working on this , just give me half an hour

**Comment by priyashuu** [comment]
im really sorry
