### ISSUE TITLE
[Feat]: The login and signup pages are being cut off at the top, making some content out of view.

### ISSUE THREAD

**Issue by sania-2912** [Tejashri-Taral/TrendTrove-Ecommerce#691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The login and signup pages are cut off at the top, causing parts of the interface to be out of view. There could be a welcome to "trend-trove" or another suggested line and a crerly defined border making the page look complete. In the login page the line-"Your fashion journey begins here!"- has been cut out while the signup page does not have complete login and signup buttons visible.

### Use Case

The login and signup pages for "Trend-Trove" are experiencing layout issues where the top sections are cut off, obscuring important elements. The welcome message, “Welcome to Trend-Trove,” and a clearly defined border are needed to enhance the page's appearance. On the login page, the message “Your fashion journey begins here!” is not fully visible, while the signup page lacks complete visibility of the login and signup buttons, impacting user experience and accessibility.
![Screenshot 2024-10-29 121738](https://github.com/user-attachments/assets/29831534-d107-4f82-bf7f-7d0b9b288295)
![Screenshot 2024-10-29 121757](https://github.com/user-attachments/assets/90ea8635-a822-4bd8-8bed-2c52bceeaab8)

### Priority

Medium

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by sania-2912** [comment]
@Tejashri-Taral kindly assign me this issue. I am sure I will be able to solve it.

**Comment by AsthaSingh22-8** [comment]
@Tejashri-Taral kindly assign me this issue.
