### ISSUE TITLE
ICONS can be fixed

### ISSUE THREAD

**Issue by sahhoArjun097** [Tejashri-Taral/TrendTrove-Ecommerce#7]
while using the hamburger the  icons are not appear properly  
![Screenshot 2024-10-01 183405](https://github.com/user-attachments/assets/4c628d8b-5280-4c17-bdd5-18f47d34ebd9)
Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant . My GitHub username is sahhoArjun097.

**Comment by maliumesh1** [comment]
Please assign this issue to me . 
https://github.com/maliumesh1

**Comment by sahhoArjun097** [comment]
please assign me this issue
