### ISSUE TITLE
highlighting the sections in the nav bar when entered into that particualar section

### ISSUE THREAD

**Issue by Varshitha713** [Tejashri-Taral/TrendTrove-Ecommerce#70]
by highlighting we can increase user experience and also it makes the design clean and the user can understand what section they are currently in
suppose if am in contact section then we can highlight the contact in the navigation bar or else we can keep an underline indicating to the user in which section they are currently in!!

**Comment by Tejashri-Taral** [comment]
Please make navbar sticky and proceed.

**Comment by hars-21** [comment]
@Varshitha713 Any Updates?? It's been a week and we haven't received any updates from you. Please respond quickly or this issue will be assigned to another contributor.
