### ISSUE TITLE
[Bug]: Text Alignment and Readability Adjustment for About Page (about.html)

### ISSUE THREAD

**Issue by DevStudyBug** [Tejashri-Taral/TrendTrove-Ecommerce#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- The text on the About page lacks consistent alignment Currently, the main title, subtitle, and paragraph text do not have a cohesive structure, impacting the visual appeal and user experience.
- Suggested changes include center-aligning the main title and subtitle, while left-aligning or justifying the paragraph text. Proper spacing between sections and line spacing within the paragraph will also be applied to improve overall readability.

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/2bb63f84-d461-4017-8a47-34c4e07a3c91)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sweksha273** [comment]
i want to contribute in the issue, please assign me the issue
