### ISSUE TITLE
The search bar looks very basic and does not have a valid design wrt to the aesthetic website.

### ISSUE THREAD

**Issue by anshdeep0504** [Tejashri-Taral/TrendTrove-Ecommerce#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The search bar looks very basic and does not have a valid design wrt to the aesthetic website.

### Add Screenshots / Video Clip

![Screenshot from 2024-10-30 05-55-27](https://github.com/user-attachments/assets/dcd4169c-86af-4533-8fca-b103af3d3ce6)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sambedan1** [comment]
Assign this task to me

**Comment by kanishkadubey16** [comment]
pls assign this issue to me.
