### ISSUE TITLE
add rating product 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [Tejashri-Taral/TrendTrove-Ecommerce#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Example:
Durability: ★★★★☆
Ease of Use: ★★★★★
Value for Money: ★★★★☆
Aesthetics: ★★★★☆

![Screenshot (461)](https://github.com/user-attachments/assets/6910ef2b-f4c9-471e-a612-690b4d9d022a)

### Use Case

A shopper is choosing between two laptops with similar specifications but wants to know which one offers better battery life, portability, and value for money.

### Benefits

Allow customers to rate specific benefits as part of their review (e.g., rate the durability, functionality, etc.), creating more relatable, user-generated content.
Display the average rating for each benefit, giving new customers insight into real user experiences.

se icons (e.g., stars, thumbs-up, or checkmarks) for each benefit rating, making it visually appealing and easy to scan.
Consider color-coding benefits (e.g., green for highly rated benefits, yellow for average) for a quick at-a-glance impact.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task

**Comment by Tejashri-Taral** [comment]
proceed!
