### ISSUE TITLE
[Feat]: Creating Site Map Page

### ISSUE THREAD

**Issue by VidhanThakur09** [Tejashri-Taral/TrendTrove-Ecommerce#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This issue proposes the creation of a site map page for the project. A site map is a visual representation of the website's structure, making it easier for users to navigate and find the information they need. It will act as a centralized hub, providing a clear overview of all the available pages and their relationships.

### Use Case

- **User Navigation:** The site map will serve as a valuable tool for users to quickly locate specific pages or sections within the website.
- **Search Engine Optimization (SEO):** A well-structured site map can improve the website's visibility in search engine results by providing a clear path for search engines to crawl and index content.
- **Accessibility:** The site map will enhance accessibility for users with disabilities, as it offers a visual representation of the website's structure.

### Benefits

- **Improved User Experience:** A site map enhances user experience by making it easier for users to find their desired information.
- **Better Search Engine Rankings:** A well-optimized site map can boost the website's search engine rankings.
- **Enhanced Accessibility:** The site map improves accessibility for users with disabilities.
- **Clearer Website Structure:** The site map provides a clear visual representation of the website's structure, making it easier to understand and maintain.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by VidhanThakur09** [comment]
@Tejashri-Taral  can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by VidhanThakur09** [comment]
@Tejashri-Taral please review this Issue.

**Comment by Tejashri-Taral** [comment]
Tomorrow will be last day do it fast so that your score reflect on leaderboard

**Comment by VidhanThakur09** [comment]
sorry mam for the delay, i am about to raise the PR
