### ISSUE TITLE
Adding  toggle button

### ISSUE THREAD

**Issue by Prachiikhar25** [Tejashri-Taral/TrendTrove-Ecommerce#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello I'd like to add a feature Implementing a toggle button to switch between different states or views.

![{CDE2AB85-D180-42A4-B5DA-1B1F61A925DA}](https://github.com/user-attachments/assets/46f3c1c2-c727-4a59-847d-1aeb2d0f082c)

### Use Case

A website offers both light and dark modes for user preference.
![{CDE2AB85-D180-42A4-B5DA-1B1F61A925DA}](https://github.com/user-attachments/assets/46f3c1c2-c727-4a59-847d-1aeb2d0f082c)

### Benefits

A toggle button is added to the website to allow users to switch between light and dark themes easily.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Srija-11** [comment]
i want to add a toggle button please assign this to me

**Comment by Mohammedmaaz541** [comment]
Subject: Request for Opportunity to Contribute totrend-trove-ecommerc

Dear 

I am writing to express my interest in contributing to the [Project Name] at [Organization's Name]. I am keen to apply and expand my skills in [relevant technologies or areas related to the project] through hands-on experience, and I believe this project aligns with my goals and expertise.

Having worked on [mention any relevant projects or skills briefly], I am confident that I can add value to the project. I am dedicated to learning and contributing effectively to the team's objectives and am willing to put in the necessary effort to ensure success.

Thank you for considering my request. I look forward to the possibility of contributing to this project and supporting [Organization’s Name]'s goals.

Best regards,
Mohammed Maaz

**Comment by Prachiikhar25** [comment]
@Tejashri-Taral please add level tag too

**Comment by Tejashri-Taral** [comment]
Added in PR
