### ISSUE TITLE
[Bug]: Women products section 

### ISSUE THREAD

**Issue by Mrunali01** [Tejashri-Taral/TrendTrove-Ecommerce#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Text seen on women products section.

### Add Screenshots / Video Clip

<img width="700" alt="image" src="https://github.com/user-attachments/assets/00543edc-3fd3-45be-a0c8-5d71f55f534a">

### What browsers are you seeing the problem on?

Microsoft Edge

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Already fixed
