### ISSUE TITLE
[Bug]: footer in About page is different from remaining all pages

### ISSUE THREAD

**Issue by laxmikandivalasa** [Tejashri-Taral/TrendTrove-Ecommerce#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A constant footer can significantly enhance the look and functionality of a website
I'd like to change it
@Tejashri-Taral @harikasayani can you assign tis to me??

### Add Screenshots / Video Clip

about page
![Screenshot (343)](https://github.com/user-attachments/assets/0e3d9032-eaeb-4394-9f89-82837e480707)
remaining pages
![Screenshot (344)](https://github.com/user-attachments/assets/37be560a-46b8-47bc-b748-6bd7501ceeb6)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by laxmikandivalasa** [comment]
@Tejashri-Taral can you assign this to me??

**Comment by Tejashri-Taral** [comment]
Proceed!
