### ISSUE TITLE
[Feat]: I want to add a wishlist functionality.

### ISSUE THREAD

**Issue by rishika105** [Tejashri-Taral/TrendTrove-Ecommerce#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to try adding a wishlist functionality where I can add and remove products from the wishlist.

### Use Case

Beacuse it will enhance the ecommerce website.

### Benefits

Every ecommerce platform has it.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by Tejashri-Taral** [comment]
any update?
