### ISSUE TITLE
Adding About Page 

### ISSUE THREAD

**Issue by NishantRana07** [Tejashri-Taral/TrendTrove-Ecommerce#74]
I can add about us page in which we can share to user, that how TrendTrove provide better services.

please assign it to me for hacktober fest and Gssoc

**Comment by prishsha** [comment]
I would also like to work on the UI/UX of this. @NishantRana07 will you be willing to collaborate on it?

**Comment by NishantRana07** [comment]
Yeah why not, share the progress with me and assign it to me
