### ISSUE TITLE
[Feat]: Enhancing the css styling of the scroll back button by adding a timeline on it.

### ISSUE THREAD

**Issue by shriyadindi** [Tejashri-Taral/TrendTrove-Ecommerce#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhancing the css styling of the scroll back button by adding a timeline on it.
![Screenshot 2024-10-31 115055](https://github.com/user-attachments/assets/65c8fcda-c2b2-4250-8015-bf1e316fd1c3)

### Use Case

Enhancing the css styling of the scroll back button by adding a timeline on it.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
Proceed!
