### ISSUE TITLE
[Feat]: Add a rate us page

### ISSUE THREAD

**Issue by TanushreeBorase** [Tejashri-Taral/TrendTrove-Ecommerce#742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Rate Us" page will provide a dedicated space where users can give feedback on their shopping experience. This page should allow users to rate their satisfaction with various aspects of the site, such as product quality, ease of navigation, customer service, and delivery experience

### Use Case

This feature would help the ecommerce platform gather valuable insights directly from customers, enabling improvements to customer experience based on real feedback. It enhances user engagement by making customers feel heard and valued.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
It's already present in feedback form
