### ISSUE TITLE
Enhance the UI of footer

### ISSUE THREAD

**Issue by Kajalmehta29** [Tejashri-Taral/TrendTrove-Ecommerce#744]
I want to change the styling and font in the footer section to make it look good.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by gayatrikate04** [comment]
I would like to work on it.

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by Kajalmehta29** [comment]
Yes, I'll create  PR within an hour.
