### ISSUE TITLE
[Bug]: Popup banner not responsive in the small devices

### ISSUE THREAD

**Issue by Hemraj-7** [Tejashri-Taral/TrendTrove-Ecommerce#770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Popup banner not looking good in the small devices like mobile phone. it is not responsive for the mobile phone. i want to make is responsive.

![Screenshot 2024-11-07 141014](https://github.com/user-attachments/assets/622b4c0c-c69b-483e-a88a-22d1f9a5dfcd)

I want to work on this issue Please assign me this issue 
Thank you!

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ShreyaPandeycode** [comment]
okay assign this to me I can fix this issue
