### ISSUE TITLE
[Bug]: About Page is not responsive

### ISSUE THREAD

**Issue by Hemraj-7** [Tejashri-Taral/TrendTrove-Ecommerce#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

About page is not responsive in the mobile phone. this is not looking good so i want to make it responsive and user friendly.

![Screenshot 2024-11-07 141514](https://github.com/user-attachments/assets/b29dc3c9-1a4b-4dfc-abdb-b230643d89fc)

Assign me this issue @Tejashri-Taral 
Thank you!

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tejashri-Taral** [comment]
@Hemraj-7 Do not spam
if you want to make pages responsive do it in only one PR
Let me know if you are willing to do it

**Comment by Hemraj-7** [comment]
> @Hemraj-7 Do not spam if you want to make pages responsive do it in only one PR Let me know if you are willing to do it

I'm not doing spam @Tejashri-Taral
