### ISSUE TITLE
[Bug]: The Search bar is not working at all in home page

### ISSUE THREAD

**Issue by pinakviramgama** [Tejashri-Taral/TrendTrove-Ecommerce#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The search bar is not working in index.html page so it can be not useful to the user

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/86b8c561-3fe3-48e1-b8cf-c8c2d7493e92)

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by pinakviramgama** [comment]
Dear @Tejashri-Taral , please assign me this issue

**Comment by pinakviramgama** [comment]
Dear @Tejashri-Taral , please assign me this issue

**Comment by Tejashri-Taral** [comment]
Proceed!
