### ISSUE TITLE
[Feat]: Adding icons to the Quicklinks

### ISSUE THREAD

**Issue by likitha-kapu** [Tejashri-Taral/TrendTrove-Ecommerce#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding icons to the Quicklinks section can significantly improve both the visual appeal and the user experience of your website's footer. Currently, the Quicklinks options might appear plain or less engaging, making it harder for users to quickly identify their purpose. By integrating relevant icons next to each Quicklink, you not only enhance the overall aesthetic but also make it easier for users to recognize the links at a glance.
![Screenshot 2024-11-08 193830](https://github.com/user-attachments/assets/733b411d-465b-43fa-9002-dd2a6b438650)

### Use Case

This addition adds a visual cue that makes navigation more intuitive, allowing users to quickly understand the link's functionality without needing to read through each label. Ultimately, using icons can create a more polished, professional, and user-friendly footer design.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by likitha-kapu** [comment]
@Tejashri-Taral please assign this task to me....I wish to work on this issue

**Comment by Tejashri-Taral** [comment]
Proceed!

**Comment by likitha-kapu** [comment]
@Tejashri-Taral please checkout my pull request and please add me a level1 label

**Comment by likitha-kapu** [comment]
@Tejashri-Taral can you add me a level1 label
