### ISSUE TITLE
Adding dark mode and light mode theme

### ISSUE THREAD

**Issue by ruchikakengal** [Tejashri-Taral/TrendTrove-Ecommerce#79]
Like to add scroll up option and add adtional changes @Tejashri-Taral Assign me I like to work on it .

**Comment by ruchikakengal** [comment]
Add Gssoc ext and hactorbefest accepted and level labels @Tejashri-Taral

**Comment by Janhavi078** [comment]
i want to add light mode to dark mode functionality in the website @Tejashri-Taral please assign me this work i like to work on it

**Comment by Tejashri-Taral** [comment]
@ruchikakengal Only add dark/light mode button

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral  Can you assign me this task as well. I have done this in my previous PR's.
