### ISSUE TITLE
[Bug]: Overlapping button on homepage 

### ISSUE THREAD

**Issue by bhat-shubham** [Tejashri-Taral/TrendTrove-Ecommerce#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

bottom of the homepage(footer) has overlapping button of visitors count that appears on top of social media links.

### Add Screenshots / Video Clip

![image](https://github.com/user-attachments/assets/a6245695-e4e9-4332-b690-0038b754c354)

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sweksha273** [comment]
the home page footer has a button (visitor count) which seems to  overlap on the social media icons present there i want to fix this issue.
Assign me the issue

**Comment by Tejashri-Taral** [comment]
@bhat-shubham
