### ISSUE TITLE
Dark mode implementation for your cool website

### ISSUE THREAD

**Issue by STDYGIT** [Tejashri-Taral/TrendTrove-Ecommerce#81]
hey @Tejashri-Taral it will be so cool if we place dark theme fro your website as the uswer experince a cool efect how here is te cool toggel with improvement according to your website
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/a910d4db-7b99-403c-8254-ed5e875b1e71)
![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/b1f0cc0c-4363-44db-8a19-f3efdbc89735)

**Comment by STDYGIT** [comment]
Sir, I would like to work on this feature and would appreciate it if you could assign it to me for Hacktoberfest and GGSOC '24. I believe this is a level 2 task, as it requires a complete overhaul of the page styles. Thank you!

**Comment by Tejashri-Taral** [comment]
Already assigned #79

**Comment by STDYGIT** [comment]
mam can you assign as you opend it again

**Comment by Tejashri-Taral** [comment]
@STDYGIT You can work on it

**Comment by Tejashri-Taral** [comment]
Level will be assign based on the work

**Comment by STDYGIT** [comment]
Mam please give level for the acceptance in gssoc

**Comment by Subham1** [comment]
mam could you pls assign me this work

**Comment by Tejashri-Taral** [comment]
@STDYGIT It's been more than a week, any updates?

**Comment by Subham1** [comment]
@Tejashri-Taral you can assign me I can work on it

**Comment by Kavish-Paraswar** [comment]
can u assign this to me

**Comment by hars-21** [comment]
@Subham1 You can start working now

**Comment by Kavish-Paraswar** [comment]
@Tejashri-Taral  can u assign it to me

**Comment by hars-21** [comment]
@Subham1 Are you working on it? Or should assign it someone else?

**Comment by Deepika14145** [comment]
Can you assign it to me #81 @hars-21

**Comment by hars-21** [comment]
@Kavish-Paraswar Start working on it.

**Comment by Kavish-Paraswar** [comment]
i have to add dark mode functionality to the whole website? @hars-21

**Comment by hars-21** [comment]
> i have to add dark mode functionality to the whole website? @hars-21

Yes. Do add it on every page.

**Comment by Kavish-Paraswar** [comment]
assign atleast 2 or level 3 for the given amount of work

**Comment by hars-21** [comment]
level will be based on work. It could be upgraded based on your contribution. So, just do quality contribution.

**Comment by Kavish-Paraswar** [comment]
please assign first then i will do all the work on the issue @hars-21

**Comment by Kavish-Paraswar** [comment]
Since this feature requires a complete dark mode implementation, it involves adjusting the entire color palette and making significant UI changes. Given the extensive work required, I recommend assigning this as a Level 3 task.

**Comment by Tejashri-Taral** [comment]
@Kavish-Paraswar Level will be added after your work on PR. Start working it's temporary level right now

**Comment by Kavish-Paraswar** [comment]
please assign this to someone else.

**Comment by Deepika14145** [comment]
Assign me @Tejashri-Taral

**Comment by Deepika14145** [comment]
Will update soon!
