### ISSUE TITLE
To adding animation effect on social media icons

### ISSUE THREAD

**Issue by Sujal1201** [Tejashri-Taral/TrendTrove-Ecommerce#812]
## Issue: animation effect on social media icons

**screenshot**

<img width="307" alt="image" src="https://github.com/user-attachments/assets/5ead3ab2-2598-45f2-9c99-7bbd3b32decb">

**Comment by Sujal1201** [comment]
Please assign me to this issue

**Comment by Tejashri-Taral** [comment]
Animation is already there
