### ISSUE TITLE
Adding the functionality of "Explore More" in the Home Page

### ISSUE THREAD

**Issue by vararaghu002** [Tejashri-Taral/TrendTrove-Ecommerce#83]

**Comment by Devanshu1603** [comment]
please assign me this under gssoc-ext level . we can re-direct the user to the products page when he/she ckick on explore-more button . please assign it to me so that i could work on this asap.

**Comment by Tejashri-Taral** [comment]
@vararaghu002 Can you elaborate your idea?

**Comment by vararaghu002** [comment]
When I click on 'Explore More,' it should navigate to display more
products. In your website, it will navigate to the 'Top Products of the
Season!' section

**Comment by Tejashri-Taral** [comment]
You can start working..

**Comment by vararaghu002** [comment]
Ok

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by vararaghu002** [comment]
When I click on 'Explore More,' should I create a new page to navigate to the product, or should I navigate directly to the same page for the product?

**Comment by Tejashri-Taral** [comment]
@vararaghu002 You can create new page which will contain some awesome products

**Comment by vararaghu002** [comment]
ok

**Comment by Tejashri-Taral** [comment]
Any updates?

**Comment by vararaghu002** [comment]
Working on it...

**Comment by hars-21** [comment]
@vararaghu002 It's been a week. Please make a PR asap or I 'll have to close this issue. Max. 3-4 days are needed for this type of issues.

**Comment by vararaghu002** [comment]
Sorry I unable to do it ...
Close this issue
