### ISSUE TITLE
Change cursor to hand pointer on hover for clickable elements

### ISSUE THREAD

**Issue by Anushka-gupta9** [Tejashri-Taral/TrendTrove-Ecommerce#84]
Currently, the cursor remains an arrow when hovering over interactive elements such as buttons or other clickable items. To enhance the user experience and make the interface more interactive, the cursor should change to a hand pointer. This change signals that the element is clickable, improving usability and creating a more engaging and user-friendly interface.

**Comment by Tejashri-Taral** [comment]
It's been more than a week also the website is updated
