### ISSUE TITLE
improve the footer 

### ISSUE THREAD

**Issue by jayanththalla** [Tejashri-Taral/TrendTrove-Ecommerce#85]
The footer UI is not good. improve the footer UI by making responesiveness 
please assign me @pa under the gssoc ext and hacktoberfest
![image](https://github.com/user-attachments/assets/b2c572da-92d2-4034-959b-4e228a0d0543)

**Comment by Suvendu-UI** [comment]
Pls assign me this issue?

**Comment by techaakritisha** [comment]
I wanna work on this . Please assign it to me

**Comment by abhishekkrjha2811** [comment]
hey assign it to me i want to work on this issue

**Comment by umeshmunde** [comment]
@jayanththalla   please assign me this as this is not resolved yet. I have good knowledge of frontend development.
