### ISSUE TITLE
Requesting re-assignment as prev acc got suspended 

### ISSUE THREAD

**Issue by hana-maria** [Tejashri-Taral/TrendTrove-Ecommerce#94]
Hi! I was assigned this issue and I raised a pr and then my acc got suspended randomly.

Kindly reassign me this so I can create a pr
![Screenshot_2024-10-03-17-03-50-23_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/user-attachments/assets/a54c5140-1c7e-45be-b00e-592e45979e5e)

**Comment by hana-maria** [comment]
@Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
Can you please elaborate more about this ?

**Comment by hana-maria** [comment]
Hi! I had made an issue about making simple changes to the buttons(some hover effects), I even raised a pr and then my acc got suspended.

**Comment by hana-maria** [comment]
@Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
Proceed!
