### ISSUE TITLE
Feat: : Add Links to Quick Links Section in Footer

### ISSUE THREAD

**Issue by HarshadaGirase** [Tejashri-Taral/TrendTrove-Ecommerce#95]
Description:
Need to enhance the user experience by adding essential links to the "Quick Links" section in the footer. This will help users access important pages easily and improve site navigation.

![footerlinks](https://github.com/user-attachments/assets/999f1940-77a6-44a7-b668-48b98a14a9d8)

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by tulikaa25** [comment]
Please assign this issue to me. @Tejashri-Taral
