### ISSUE TITLE
add "scroll to top" button to the website and make it responsive

### ISSUE THREAD

**Issue by sambedan1** [Tejashri-Taral/TrendTrove-Ecommerce#97]
1-Implement a "Scroll to Top" button that appears when users scroll down the page.
2-Ensure the button is easily visible and matches the website's design.
3-Make the button functional, allowing smooth scrolling back to the top of the page when clicked.
please assign this task to me

**Comment by rutikakengal** [comment]
I like to add scroll to top button to the website @Tejashri-Taral Assign me I like to work on it

**Comment by sambedan1** [comment]
assign this task to me
