### ISSUE TITLE
BUG: Hamburger Appears on the Sneaker Page

### ISSUE THREAD

**Issue by jjf2009** [Tejashri-Taral/TrendTrove-Ecommerce#98]
Description:
The Hamburger is appearing under the TrendTrove logo in the Sneaker Page

 Steps to Reproduce 
1. Step 1: Go to TrendTrove website
2. Step 2: Click on Shop Sneakers 

 Current Behavior
The Hamburger is appearing under the TrendTrove logo 

Expected Behavior
The Hamburger is should appearing only in mobile

Screenshots

![Screenshot 2024-10-03 202754](https://github.com/user-attachments/assets/252c989b-38a9-420b-8cc4-8f7b6a7bc23d)

 Suggested Improvements
1. Make the sneaker Page Responsive

**Comment by jjf2009** [comment]
Kindly assign me this issue

**Comment by tulikaa25** [comment]
Please assign this issue to me. @Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
@jjf2009 Can you please also integrate navbar same as the homepage?

**Comment by jjf2009** [comment]
> @jjf2009 Can you please also integrate navbar same as the homepage?

ok
